// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-form.proto

package grpcform

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type STATUS int32

const (
	STATUS_ACTIVE   STATUS = 0
	STATUS_REQUIRED STATUS = 1
	STATUS_DISABLED STATUS = 2
	STATUS_HIDDEN   STATUS = 3
)

var STATUS_name = map[int32]string{
	0: "ACTIVE",
	1: "REQUIRED",
	2: "DISABLED",
	3: "HIDDEN",
}

var STATUS_value = map[string]int32{
	"ACTIVE":   0,
	"REQUIRED": 1,
	"DISABLED": 2,
	"HIDDEN":   3,
}

func (x STATUS) String() string {
	return proto.EnumName(STATUS_name, int32(x))
}

func (STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{0}
}

type BUTTON_FUNC int32

const (
	BUTTON_FUNC_VALIDATE BUTTON_FUNC = 0
	BUTTON_FUNC_RESET    BUTTON_FUNC = 1
	BUTTON_FUNC_SEND     BUTTON_FUNC = 2
)

var BUTTON_FUNC_name = map[int32]string{
	0: "VALIDATE",
	1: "RESET",
	2: "SEND",
}

var BUTTON_FUNC_value = map[string]int32{
	"VALIDATE": 0,
	"RESET":    1,
	"SEND":     2,
}

func (x BUTTON_FUNC) String() string {
	return proto.EnumName(BUTTON_FUNC_name, int32(x))
}

func (BUTTON_FUNC) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{1}
}

type GetFormRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFormRequest) Reset()         { *m = GetFormRequest{} }
func (m *GetFormRequest) String() string { return proto.CompactTextString(m) }
func (*GetFormRequest) ProtoMessage()    {}
func (*GetFormRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{0}
}

func (m *GetFormRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFormRequest.Unmarshal(m, b)
}
func (m *GetFormRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFormRequest.Marshal(b, m, deterministic)
}
func (m *GetFormRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFormRequest.Merge(m, src)
}
func (m *GetFormRequest) XXX_Size() int {
	return xxx_messageInfo_GetFormRequest.Size(m)
}
func (m *GetFormRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFormRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFormRequest proto.InternalMessageInfo

func (m *GetFormRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SendFormResponse struct {
	Form                 *Form    `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	Succeed              bool     `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendFormResponse) Reset()         { *m = SendFormResponse{} }
func (m *SendFormResponse) String() string { return proto.CompactTextString(m) }
func (*SendFormResponse) ProtoMessage()    {}
func (*SendFormResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{1}
}

func (m *SendFormResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendFormResponse.Unmarshal(m, b)
}
func (m *SendFormResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendFormResponse.Marshal(b, m, deterministic)
}
func (m *SendFormResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendFormResponse.Merge(m, src)
}
func (m *SendFormResponse) XXX_Size() int {
	return xxx_messageInfo_SendFormResponse.Size(m)
}
func (m *SendFormResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendFormResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendFormResponse proto.InternalMessageInfo

func (m *SendFormResponse) GetForm() *Form {
	if m != nil {
		return m.Form
	}
	return nil
}

func (m *SendFormResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func (m *SendFormResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Form struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields               []*Field  `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Buttons              []*Button `protobuf:"bytes,3,rep,name=buttons,proto3" json:"buttons,omitempty"`
	Valid                bool      `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Form) Reset()         { *m = Form{} }
func (m *Form) String() string { return proto.CompactTextString(m) }
func (*Form) ProtoMessage()    {}
func (*Form) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{2}
}

func (m *Form) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Form.Unmarshal(m, b)
}
func (m *Form) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Form.Marshal(b, m, deterministic)
}
func (m *Form) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Form.Merge(m, src)
}
func (m *Form) XXX_Size() int {
	return xxx_messageInfo_Form.Size(m)
}
func (m *Form) XXX_DiscardUnknown() {
	xxx_messageInfo_Form.DiscardUnknown(m)
}

var xxx_messageInfo_Form proto.InternalMessageInfo

func (m *Form) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Form) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Form) GetButtons() []*Button {
	if m != nil {
		return m.Buttons
	}
	return nil
}

func (m *Form) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type Field struct {
	Label                string      `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Status               STATUS      `protobuf:"varint,2,opt,name=status,proto3,enum=grpcform.STATUS" json:"status,omitempty"`
	ActiveIf             *ActiveIf   `protobuf:"bytes,3,opt,name=activeIf,proto3" json:"activeIf,omitempty"`
	RequiredIf           *RequiredIf `protobuf:"bytes,4,opt,name=requiredIf,proto3" json:"requiredIf,omitempty"`
	DisabledIf           *DisabledIf `protobuf:"bytes,5,opt,name=disabledIf,proto3" json:"disabledIf,omitempty"`
	HiddenIf             *HiddenIf   `protobuf:"bytes,6,opt,name=hiddenIf,proto3" json:"hiddenIf,omitempty"`
	InstantValidate      bool        `protobuf:"varint,7,opt,name=instant_validate,json=instantValidate,proto3" json:"instant_validate,omitempty"`
	Error                string      `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	Input                *Input      `protobuf:"bytes,9,opt,name=input,proto3" json:"input,omitempty"`
	RadioGroup           *RadioGroup `protobuf:"bytes,10,opt,name=radio_group,json=radioGroup,proto3" json:"radio_group,omitempty"`
	Select               *Select     `protobuf:"bytes,11,opt,name=select,proto3" json:"select,omitempty"`
	Slider               *Slider     `protobuf:"bytes,12,opt,name=slider,proto3" json:"slider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{3}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Field) GetStatus() STATUS {
	if m != nil {
		return m.Status
	}
	return STATUS_ACTIVE
}

func (m *Field) GetActiveIf() *ActiveIf {
	if m != nil {
		return m.ActiveIf
	}
	return nil
}

func (m *Field) GetRequiredIf() *RequiredIf {
	if m != nil {
		return m.RequiredIf
	}
	return nil
}

func (m *Field) GetDisabledIf() *DisabledIf {
	if m != nil {
		return m.DisabledIf
	}
	return nil
}

func (m *Field) GetHiddenIf() *HiddenIf {
	if m != nil {
		return m.HiddenIf
	}
	return nil
}

func (m *Field) GetInstantValidate() bool {
	if m != nil {
		return m.InstantValidate
	}
	return false
}

func (m *Field) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Field) GetInput() *Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Field) GetRadioGroup() *RadioGroup {
	if m != nil {
		return m.RadioGroup
	}
	return nil
}

func (m *Field) GetSelect() *Select {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *Field) GetSlider() *Slider {
	if m != nil {
		return m.Slider
	}
	return nil
}

type ActiveIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ActiveIf) Reset()         { *m = ActiveIf{} }
func (m *ActiveIf) String() string { return proto.CompactTextString(m) }
func (*ActiveIf) ProtoMessage()    {}
func (*ActiveIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{4}
}

func (m *ActiveIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveIf.Unmarshal(m, b)
}
func (m *ActiveIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveIf.Marshal(b, m, deterministic)
}
func (m *ActiveIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveIf.Merge(m, src)
}
func (m *ActiveIf) XXX_Size() int {
	return xxx_messageInfo_ActiveIf.Size(m)
}
func (m *ActiveIf) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveIf.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveIf proto.InternalMessageInfo

func (m *ActiveIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type RequiredIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RequiredIf) Reset()         { *m = RequiredIf{} }
func (m *RequiredIf) String() string { return proto.CompactTextString(m) }
func (*RequiredIf) ProtoMessage()    {}
func (*RequiredIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{5}
}

func (m *RequiredIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequiredIf.Unmarshal(m, b)
}
func (m *RequiredIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequiredIf.Marshal(b, m, deterministic)
}
func (m *RequiredIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequiredIf.Merge(m, src)
}
func (m *RequiredIf) XXX_Size() int {
	return xxx_messageInfo_RequiredIf.Size(m)
}
func (m *RequiredIf) XXX_DiscardUnknown() {
	xxx_messageInfo_RequiredIf.DiscardUnknown(m)
}

var xxx_messageInfo_RequiredIf proto.InternalMessageInfo

func (m *RequiredIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type DisabledIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DisabledIf) Reset()         { *m = DisabledIf{} }
func (m *DisabledIf) String() string { return proto.CompactTextString(m) }
func (*DisabledIf) ProtoMessage()    {}
func (*DisabledIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{6}
}

func (m *DisabledIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisabledIf.Unmarshal(m, b)
}
func (m *DisabledIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisabledIf.Marshal(b, m, deterministic)
}
func (m *DisabledIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisabledIf.Merge(m, src)
}
func (m *DisabledIf) XXX_Size() int {
	return xxx_messageInfo_DisabledIf.Size(m)
}
func (m *DisabledIf) XXX_DiscardUnknown() {
	xxx_messageInfo_DisabledIf.DiscardUnknown(m)
}

var xxx_messageInfo_DisabledIf proto.InternalMessageInfo

func (m *DisabledIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type HiddenIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HiddenIf) Reset()         { *m = HiddenIf{} }
func (m *HiddenIf) String() string { return proto.CompactTextString(m) }
func (*HiddenIf) ProtoMessage()    {}
func (*HiddenIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{7}
}

func (m *HiddenIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiddenIf.Unmarshal(m, b)
}
func (m *HiddenIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiddenIf.Marshal(b, m, deterministic)
}
func (m *HiddenIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiddenIf.Merge(m, src)
}
func (m *HiddenIf) XXX_Size() int {
	return xxx_messageInfo_HiddenIf.Size(m)
}
func (m *HiddenIf) XXX_DiscardUnknown() {
	xxx_messageInfo_HiddenIf.DiscardUnknown(m)
}

var xxx_messageInfo_HiddenIf proto.InternalMessageInfo

func (m *HiddenIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type Validator struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	EqualText            string   `protobuf:"bytes,2,opt,name=equal_text,json=equalText,proto3" json:"equal_text,omitempty"`
	EqualOption          *Option  `protobuf:"bytes,3,opt,name=equal_option,json=equalOption,proto3" json:"equal_option,omitempty"`
	EqualNumber          int64    `protobuf:"varint,4,opt,name=equal_number,json=equalNumber,proto3" json:"equal_number,omitempty"`
	SmallerThanNumber    int64    `protobuf:"varint,5,opt,name=smaller_than_number,json=smallerThanNumber,proto3" json:"smaller_than_number,omitempty"`
	GreaterThanNumber    int64    `protobuf:"varint,6,opt,name=greater_than_number,json=greaterThanNumber,proto3" json:"greater_than_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{8}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Validator) GetEqualText() string {
	if m != nil {
		return m.EqualText
	}
	return ""
}

func (m *Validator) GetEqualOption() *Option {
	if m != nil {
		return m.EqualOption
	}
	return nil
}

func (m *Validator) GetEqualNumber() int64 {
	if m != nil {
		return m.EqualNumber
	}
	return 0
}

func (m *Validator) GetSmallerThanNumber() int64 {
	if m != nil {
		return m.SmallerThanNumber
	}
	return 0
}

func (m *Validator) GetGreaterThanNumber() int64 {
	if m != nil {
		return m.GreaterThanNumber
	}
	return 0
}

type Input struct {
	Value                string     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Placeholder          string     `protobuf:"bytes,2,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Options              []*Option  `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	MinLength            *MinLength `protobuf:"bytes,4,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	MaxLength            *MaxLength `protobuf:"bytes,5,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	Regex                *Regex     `protobuf:"bytes,6,opt,name=regex,proto3" json:"regex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{9}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Input) GetPlaceholder() string {
	if m != nil {
		return m.Placeholder
	}
	return ""
}

func (m *Input) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Input) GetMinLength() *MinLength {
	if m != nil {
		return m.MinLength
	}
	return nil
}

func (m *Input) GetMaxLength() *MaxLength {
	if m != nil {
		return m.MaxLength
	}
	return nil
}

func (m *Input) GetRegex() *Regex {
	if m != nil {
		return m.Regex
	}
	return nil
}

type RadioGroup struct {
	Value                int64     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Options              []*Option `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RadioGroup) Reset()         { *m = RadioGroup{} }
func (m *RadioGroup) String() string { return proto.CompactTextString(m) }
func (*RadioGroup) ProtoMessage()    {}
func (*RadioGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{10}
}

func (m *RadioGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RadioGroup.Unmarshal(m, b)
}
func (m *RadioGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RadioGroup.Marshal(b, m, deterministic)
}
func (m *RadioGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RadioGroup.Merge(m, src)
}
func (m *RadioGroup) XXX_Size() int {
	return xxx_messageInfo_RadioGroup.Size(m)
}
func (m *RadioGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_RadioGroup.DiscardUnknown(m)
}

var xxx_messageInfo_RadioGroup proto.InternalMessageInfo

func (m *RadioGroup) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *RadioGroup) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type Select struct {
	Value                int64     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Placeholder          string    `protobuf:"bytes,2,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Options              []*Option `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Select) Reset()         { *m = Select{} }
func (m *Select) String() string { return proto.CompactTextString(m) }
func (*Select) ProtoMessage()    {}
func (*Select) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{11}
}

func (m *Select) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Select.Unmarshal(m, b)
}
func (m *Select) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Select.Marshal(b, m, deterministic)
}
func (m *Select) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Select.Merge(m, src)
}
func (m *Select) XXX_Size() int {
	return xxx_messageInfo_Select.Size(m)
}
func (m *Select) XXX_DiscardUnknown() {
	xxx_messageInfo_Select.DiscardUnknown(m)
}

var xxx_messageInfo_Select proto.InternalMessageInfo

func (m *Select) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Select) GetPlaceholder() string {
	if m != nil {
		return m.Placeholder
	}
	return ""
}

func (m *Select) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type Slider struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Min                  int64    `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int64    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Step                 int64    `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Slider) Reset()         { *m = Slider{} }
func (m *Slider) String() string { return proto.CompactTextString(m) }
func (*Slider) ProtoMessage()    {}
func (*Slider) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{12}
}

func (m *Slider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slider.Unmarshal(m, b)
}
func (m *Slider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slider.Marshal(b, m, deterministic)
}
func (m *Slider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slider.Merge(m, src)
}
func (m *Slider) XXX_Size() int {
	return xxx_messageInfo_Slider.Size(m)
}
func (m *Slider) XXX_DiscardUnknown() {
	xxx_messageInfo_Slider.DiscardUnknown(m)
}

var xxx_messageInfo_Slider proto.InternalMessageInfo

func (m *Slider) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Slider) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Slider) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Slider) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

type Option struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{13}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Option) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MinLength struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinLength) Reset()         { *m = MinLength{} }
func (m *MinLength) String() string { return proto.CompactTextString(m) }
func (*MinLength) ProtoMessage()    {}
func (*MinLength) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{14}
}

func (m *MinLength) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinLength.Unmarshal(m, b)
}
func (m *MinLength) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinLength.Marshal(b, m, deterministic)
}
func (m *MinLength) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinLength.Merge(m, src)
}
func (m *MinLength) XXX_Size() int {
	return xxx_messageInfo_MinLength.Size(m)
}
func (m *MinLength) XXX_DiscardUnknown() {
	xxx_messageInfo_MinLength.DiscardUnknown(m)
}

var xxx_messageInfo_MinLength proto.InternalMessageInfo

func (m *MinLength) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *MinLength) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type MaxLength struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxLength) Reset()         { *m = MaxLength{} }
func (m *MaxLength) String() string { return proto.CompactTextString(m) }
func (*MaxLength) ProtoMessage()    {}
func (*MaxLength) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{15}
}

func (m *MaxLength) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxLength.Unmarshal(m, b)
}
func (m *MaxLength) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxLength.Marshal(b, m, deterministic)
}
func (m *MaxLength) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxLength.Merge(m, src)
}
func (m *MaxLength) XXX_Size() int {
	return xxx_messageInfo_MaxLength.Size(m)
}
func (m *MaxLength) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxLength.DiscardUnknown(m)
}

var xxx_messageInfo_MaxLength proto.InternalMessageInfo

func (m *MaxLength) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *MaxLength) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Regex struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Regex) Reset()         { *m = Regex{} }
func (m *Regex) String() string { return proto.CompactTextString(m) }
func (*Regex) ProtoMessage()    {}
func (*Regex) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{16}
}

func (m *Regex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Regex.Unmarshal(m, b)
}
func (m *Regex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Regex.Marshal(b, m, deterministic)
}
func (m *Regex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Regex.Merge(m, src)
}
func (m *Regex) XXX_Size() int {
	return xxx_messageInfo_Regex.Size(m)
}
func (m *Regex) XXX_DiscardUnknown() {
	xxx_messageInfo_Regex.DiscardUnknown(m)
}

var xxx_messageInfo_Regex proto.InternalMessageInfo

func (m *Regex) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Regex) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Button struct {
	Label                string      `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Status               STATUS      `protobuf:"varint,2,opt,name=status,proto3,enum=grpcform.STATUS" json:"status,omitempty"`
	ButtonFunc           BUTTON_FUNC `protobuf:"varint,3,opt,name=button_func,json=buttonFunc,proto3,enum=grpcform.BUTTON_FUNC" json:"button_func,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Button) Reset()         { *m = Button{} }
func (m *Button) String() string { return proto.CompactTextString(m) }
func (*Button) ProtoMessage()    {}
func (*Button) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{17}
}

func (m *Button) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Button.Unmarshal(m, b)
}
func (m *Button) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Button.Marshal(b, m, deterministic)
}
func (m *Button) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Button.Merge(m, src)
}
func (m *Button) XXX_Size() int {
	return xxx_messageInfo_Button.Size(m)
}
func (m *Button) XXX_DiscardUnknown() {
	xxx_messageInfo_Button.DiscardUnknown(m)
}

var xxx_messageInfo_Button proto.InternalMessageInfo

func (m *Button) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Button) GetStatus() STATUS {
	if m != nil {
		return m.Status
	}
	return STATUS_ACTIVE
}

func (m *Button) GetButtonFunc() BUTTON_FUNC {
	if m != nil {
		return m.ButtonFunc
	}
	return BUTTON_FUNC_VALIDATE
}

func init() {
	proto.RegisterEnum("grpcform.STATUS", STATUS_name, STATUS_value)
	proto.RegisterEnum("grpcform.BUTTON_FUNC", BUTTON_FUNC_name, BUTTON_FUNC_value)
	proto.RegisterType((*GetFormRequest)(nil), "grpcform.GetFormRequest")
	proto.RegisterType((*SendFormResponse)(nil), "grpcform.SendFormResponse")
	proto.RegisterType((*Form)(nil), "grpcform.Form")
	proto.RegisterType((*Field)(nil), "grpcform.Field")
	proto.RegisterType((*ActiveIf)(nil), "grpcform.ActiveIf")
	proto.RegisterType((*RequiredIf)(nil), "grpcform.RequiredIf")
	proto.RegisterType((*DisabledIf)(nil), "grpcform.DisabledIf")
	proto.RegisterType((*HiddenIf)(nil), "grpcform.HiddenIf")
	proto.RegisterType((*Validator)(nil), "grpcform.Validator")
	proto.RegisterType((*Input)(nil), "grpcform.Input")
	proto.RegisterType((*RadioGroup)(nil), "grpcform.RadioGroup")
	proto.RegisterType((*Select)(nil), "grpcform.Select")
	proto.RegisterType((*Slider)(nil), "grpcform.Slider")
	proto.RegisterType((*Option)(nil), "grpcform.Option")
	proto.RegisterType((*MinLength)(nil), "grpcform.MinLength")
	proto.RegisterType((*MaxLength)(nil), "grpcform.MaxLength")
	proto.RegisterType((*Regex)(nil), "grpcform.Regex")
	proto.RegisterType((*Button)(nil), "grpcform.Button")
}

func init() { proto.RegisterFile("grpc-form.proto", fileDescriptor_875c494c6e4805a2) }

var fileDescriptor_875c494c6e4805a2 = []byte{
	// 986 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdf, 0x6f, 0x23, 0x35,
	0x10, 0xbe, 0xcd, 0x8f, 0x6d, 0x32, 0x5b, 0xb5, 0x8b, 0xef, 0x90, 0x56, 0x27, 0x21, 0x95, 0x15,
	0x88, 0x52, 0x89, 0xea, 0x94, 0xde, 0x01, 0x0f, 0x48, 0xa7, 0xf4, 0x92, 0xde, 0x45, 0x2a, 0x39,
	0xe1, 0xa4, 0x79, 0xe0, 0x25, 0x72, 0xb2, 0x4e, 0xb2, 0x68, 0xb3, 0x9b, 0x7a, 0xbd, 0x55, 0x1e,
	0x79, 0x81, 0xbf, 0x87, 0x3f, 0x0f, 0xf1, 0x84, 0x3c, 0xf6, 0xfe, 0x68, 0x9a, 0x0a, 0x51, 0x78,
	0xf3, 0xcc, 0xf7, 0x7d, 0x63, 0x7b, 0xc6, 0x63, 0x1b, 0x8e, 0x97, 0x62, 0x33, 0xff, 0x66, 0x91,
	0x88, 0xf5, 0xf9, 0x46, 0x24, 0x32, 0x21, 0x2d, 0xe5, 0x50, 0xb6, 0xff, 0x05, 0x1c, 0xbd, 0xe7,
	0xf2, 0x2a, 0x11, 0x6b, 0xca, 0x6f, 0x33, 0x9e, 0x4a, 0x42, 0xa0, 0x11, 0xb3, 0x35, 0xf7, 0xac,
	0x13, 0xeb, 0xb4, 0x4d, 0x71, 0xec, 0xff, 0x02, 0xee, 0x88, 0xc7, 0x81, 0xa6, 0xa5, 0x9b, 0x24,
	0x4e, 0x39, 0xf1, 0xa1, 0xa1, 0x22, 0x20, 0xcf, 0xe9, 0x1c, 0x9d, 0xe7, 0x21, 0xcf, 0x91, 0x85,
	0x18, 0xf1, 0xe0, 0x20, 0xcd, 0xe6, 0x73, 0xce, 0x03, 0xaf, 0x76, 0x62, 0x9d, 0xb6, 0x68, 0x6e,
	0x2a, 0x64, 0xcd, 0xd3, 0x94, 0x2d, 0xb9, 0x57, 0xc7, 0x89, 0x72, 0xd3, 0xff, 0xcd, 0x82, 0x86,
	0x0a, 0xb1, 0x6f, 0x21, 0xe4, 0x2b, 0xb0, 0x17, 0x21, 0x8f, 0x82, 0xd4, 0xab, 0x9d, 0xd4, 0x4f,
	0x9d, 0xce, 0x71, 0x65, 0x5a, 0xe5, 0xa7, 0x06, 0x26, 0x67, 0x70, 0x30, 0xcb, 0xa4, 0x4c, 0xe2,
	0xd4, 0xab, 0x23, 0xd3, 0x2d, 0x99, 0x97, 0x08, 0xd0, 0x9c, 0x40, 0x5e, 0x40, 0xf3, 0x8e, 0x45,
	0x61, 0xe0, 0x35, 0x70, 0x8d, 0xda, 0xf0, 0x7f, 0x6f, 0x40, 0x13, 0x63, 0x2a, 0x3c, 0x62, 0x33,
	0x1e, 0x99, 0x95, 0x68, 0x83, 0x9c, 0x82, 0x9d, 0x4a, 0x26, 0xb3, 0x14, 0xb7, 0x76, 0x54, 0x9d,
	0x60, 0x34, 0xee, 0x8e, 0x6f, 0x46, 0xd4, 0xe0, 0xe4, 0x1c, 0x5a, 0x6c, 0x2e, 0xc3, 0x3b, 0x3e,
	0x58, 0xe0, 0x66, 0x9d, 0x0e, 0x29, 0xb9, 0x5d, 0x83, 0xd0, 0x82, 0x43, 0x5e, 0x03, 0x08, 0x7e,
	0x9b, 0x85, 0x82, 0x07, 0x83, 0x05, 0x2e, 0xca, 0xe9, 0xbc, 0x28, 0x15, 0xb4, 0xc0, 0x68, 0x85,
	0xa7, 0x54, 0x41, 0x98, 0xb2, 0x59, 0x84, 0xaa, 0xe6, 0xae, 0xaa, 0x57, 0x60, 0xb4, 0xc2, 0x53,
	0x6b, 0x5b, 0x85, 0x41, 0xc0, 0xe3, 0xc1, 0xc2, 0xb3, 0x77, 0xd7, 0xf6, 0xc1, 0x20, 0xb4, 0xe0,
	0x90, 0xaf, 0xc1, 0x0d, 0xe3, 0x54, 0xb2, 0x58, 0x4e, 0x31, 0x4d, 0x4c, 0x72, 0xef, 0x00, 0xd3,
	0x76, 0x6c, 0xfc, 0x13, 0xe3, 0x56, 0x69, 0xe3, 0x42, 0x24, 0xc2, 0x6b, 0xe9, 0xb4, 0xa1, 0x41,
	0xbe, 0x84, 0x66, 0x18, 0x6f, 0x32, 0xe9, 0xb5, 0x71, 0xb6, 0x4a, 0x01, 0x07, 0xca, 0x4d, 0x35,
	0x4a, 0xde, 0x80, 0x23, 0x58, 0x10, 0x26, 0xd3, 0xa5, 0x48, 0xb2, 0x8d, 0x07, 0x0f, 0x92, 0xa0,
	0xc0, 0xf7, 0x0a, 0xa3, 0x20, 0x8a, 0x31, 0x16, 0x85, 0x47, 0x7c, 0x2e, 0x3d, 0x07, 0x15, 0xd5,
	0xa2, 0xa0, 0x9f, 0x1a, 0x1c, 0x99, 0x51, 0x18, 0x70, 0xe1, 0x1d, 0x3e, 0x60, 0xa2, 0x9f, 0x1a,
	0xdc, 0x7f, 0x0b, 0xad, 0xbc, 0x48, 0xe4, 0x02, 0xc0, 0x6c, 0x3b, 0x11, 0xa9, 0x67, 0xe1, 0xc9,
	0x7a, 0x5e, 0x2a, 0x27, 0x39, 0x46, 0x2b, 0x34, 0xbf, 0x0b, 0x50, 0xd6, 0xec, 0xc9, 0x21, 0xca,
	0x02, 0x3e, 0x2d, 0xc4, 0x5b, 0x68, 0xe5, 0xf5, 0x7c, 0x5a, 0x80, 0x3f, 0x2d, 0x68, 0x17, 0x88,
	0xaa, 0x6e, 0x18, 0x07, 0x7c, 0x8b, 0x4d, 0x51, 0xa7, 0xda, 0x20, 0x9f, 0x01, 0xf0, 0xdb, 0x8c,
	0x45, 0x53, 0xc9, 0xb7, 0x12, 0x1b, 0xa3, 0x4d, 0xdb, 0xe8, 0x19, 0xf3, 0xad, 0x24, 0x17, 0x70,
	0xa8, 0xe1, 0x64, 0x23, 0xc3, 0x24, 0x36, 0xdd, 0x50, 0x49, 0xfd, 0x47, 0xf4, 0x53, 0x07, 0x59,
	0xda, 0x20, 0x9f, 0xe7, 0xa2, 0x38, 0x5b, 0xcf, 0xb8, 0xc0, 0x86, 0xa8, 0x1b, 0xca, 0x10, 0x5d,
	0xe4, 0x1c, 0x9e, 0xa7, 0x6b, 0x16, 0x45, 0x5c, 0x4c, 0xe5, 0x8a, 0xc5, 0x39, 0xb3, 0x89, 0xcc,
	0x4f, 0x0c, 0x34, 0x5e, 0xb1, 0xb8, 0xe4, 0x2f, 0x05, 0x67, 0x72, 0x87, 0x6f, 0x6b, 0xbe, 0x81,
	0x4a, 0xbe, 0xff, 0x97, 0x05, 0x4d, 0x3c, 0x9e, 0xe6, 0xae, 0xc8, 0xf2, 0x5b, 0x49, 0x1b, 0xe4,
	0x04, 0x9c, 0x4d, 0xc4, 0xe6, 0x7c, 0x95, 0x44, 0xea, 0x44, 0xe9, 0x7d, 0x57, 0x5d, 0xea, 0x3e,
	0xd2, 0x7b, 0xde, 0x73, 0x1f, 0x99, 0x4d, 0xe7, 0x04, 0xd2, 0x01, 0x58, 0x87, 0xf1, 0x34, 0xe2,
	0xf1, 0x52, 0xae, 0x4c, 0xff, 0x57, 0xaa, 0xf3, 0x63, 0x18, 0x5f, 0x23, 0x44, 0xdb, 0xeb, 0x7c,
	0x88, 0x1a, 0xb6, 0xcd, 0x35, 0xcd, 0x07, 0x1a, 0xb6, 0x2d, 0x34, 0xf9, 0x50, 0xb5, 0xa2, 0xe0,
	0x4b, 0xbe, 0x35, 0x8d, 0x7f, 0x5c, 0xbd, 0x62, 0x96, 0x7c, 0x4b, 0x35, 0xea, 0x0f, 0x01, 0xca,
	0x6e, 0xbb, 0x9f, 0x80, 0x7a, 0x9e, 0x80, 0xca, 0xf6, 0x6a, 0xff, 0xb0, 0x3d, 0x3f, 0x02, 0x5b,
	0xf7, 0xe2, 0x23, 0xb1, 0xfe, 0xd7, 0x64, 0xfa, 0x13, 0xb0, 0x75, 0x3f, 0x3f, 0x32, 0x9b, 0x0b,
	0xf5, 0x75, 0x18, 0xe3, 0x2c, 0x75, 0xaa, 0x86, 0xe8, 0x61, 0x5b, 0x3c, 0x9b, 0xca, 0xc3, 0xb6,
	0xea, 0x25, 0x4a, 0x25, 0xdf, 0x98, 0x93, 0x87, 0x63, 0xff, 0x35, 0xd8, 0xe6, 0x7c, 0xee, 0xef,
	0x84, 0x62, 0xb6, 0x5a, 0xe5, 0xa0, 0xf8, 0xdf, 0x41, 0xbb, 0x28, 0xdf, 0x23, 0x0b, 0x2a, 0xae,
	0xcd, 0x5a, 0xe5, 0xda, 0x44, 0x61, 0x51, 0xb8, 0x7f, 0x23, 0xbc, 0x80, 0x26, 0x56, 0xf3, 0x91,
	0x93, 0xbb, 0x5f, 0xf4, 0xab, 0x05, 0xb6, 0x7e, 0x25, 0xff, 0xf3, 0xe3, 0xf7, 0x2d, 0x38, 0xfa,
	0x9d, 0x9d, 0x2e, 0xb2, 0x78, 0x8e, 0x59, 0x3d, 0xea, 0x7c, 0x5a, 0x79, 0x8c, 0x6f, 0xc6, 0xe3,
	0x8f, 0xc3, 0xe9, 0xd5, 0xcd, 0xf0, 0x1d, 0x05, 0xcd, 0xbc, 0xca, 0xe2, 0xf9, 0xd9, 0x0f, 0x60,
	0xeb, 0x48, 0x04, 0xc0, 0xee, 0xbe, 0x1b, 0x0f, 0x26, 0x7d, 0xf7, 0x19, 0x39, 0x84, 0x16, 0xed,
	0xff, 0x74, 0x33, 0xa0, 0xfd, 0x9e, 0x6b, 0x29, 0xab, 0x37, 0x18, 0x75, 0x2f, 0xaf, 0xfb, 0x3d,
	0xb7, 0xa6, 0x78, 0x1f, 0x06, 0xbd, 0x5e, 0x7f, 0xe8, 0xd6, 0xcf, 0x5e, 0x81, 0x53, 0x09, 0xac,
	0x88, 0x93, 0xee, 0xf5, 0xa0, 0xd7, 0x1d, 0xab, 0x20, 0x6d, 0x68, 0xd2, 0xfe, 0xa8, 0x3f, 0x76,
	0x2d, 0xd2, 0x82, 0xc6, 0xa8, 0x3f, 0xec, 0xb9, 0xb5, 0xce, 0x1f, 0x16, 0x38, 0xea, 0xdb, 0x31,
	0xe2, 0xe2, 0x2e, 0x9c, 0x73, 0xf2, 0x06, 0x0e, 0xcc, 0xc7, 0x88, 0x78, 0xe5, 0x6a, 0xef, 0xff,
	0x95, 0x5e, 0xee, 0xfc, 0x7a, 0xfc, 0x67, 0xe4, 0x15, 0x1c, 0xe6, 0x0f, 0x20, 0x6a, 0x77, 0x18,
	0x7b, 0x14, 0xdf, 0x43, 0x2b, 0xff, 0x5b, 0x3d, 0x60, 0xbf, 0xac, 0x3e, 0x5f, 0xf7, 0xff, 0x5f,
	0xfe, 0xb3, 0x4b, 0xf8, 0xb9, 0xf8, 0xc7, 0xcd, 0x6c, 0xfc, 0xd8, 0x5d, 0xfc, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x7b, 0xb0, 0xc8, 0xda, 0xeb, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FormServiceClient is the client API for FormService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FormServiceClient interface {
	GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*Form, error)
	ValidateForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*Form, error)
	SendForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*SendFormResponse, error)
}

type formServiceClient struct {
	cc *grpc.ClientConn
}

func NewFormServiceClient(cc *grpc.ClientConn) FormServiceClient {
	return &formServiceClient{cc}
}

func (c *formServiceClient) GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*Form, error) {
	out := new(Form)
	err := c.cc.Invoke(ctx, "/grpcform.FormService/GetForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) ValidateForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*Form, error) {
	out := new(Form)
	err := c.cc.Invoke(ctx, "/grpcform.FormService/ValidateForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) SendForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*SendFormResponse, error) {
	out := new(SendFormResponse)
	err := c.cc.Invoke(ctx, "/grpcform.FormService/SendForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormServiceServer is the server API for FormService service.
type FormServiceServer interface {
	GetForm(context.Context, *GetFormRequest) (*Form, error)
	ValidateForm(context.Context, *Form) (*Form, error)
	SendForm(context.Context, *Form) (*SendFormResponse, error)
}

func RegisterFormServiceServer(s *grpc.Server, srv FormServiceServer) {
	s.RegisterService(&_FormService_serviceDesc, srv)
}

func _FormService_GetForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).GetForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcform.FormService/GetForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormServiceServer).GetForm(ctx, req.(*GetFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_ValidateForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Form)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).ValidateForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcform.FormService/ValidateForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormServiceServer).ValidateForm(ctx, req.(*Form))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_SendForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Form)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).SendForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcform.FormService/SendForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormServiceServer).SendForm(ctx, req.(*Form))
	}
	return interceptor(ctx, in, info, handler)
}

var _FormService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcform.FormService",
	HandlerType: (*FormServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetForm",
			Handler:    _FormService_GetForm_Handler,
		},
		{
			MethodName: "ValidateForm",
			Handler:    _FormService_ValidateForm_Handler,
		},
		{
			MethodName: "SendForm",
			Handler:    _FormService_SendForm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-form.proto",
}
