// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-form.proto

package grpcform

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_ACTIVE             Status = 1
	Status_REQUIRED           Status = 2
	Status_DISABLED           Status = 3
	Status_HIDDEN             Status = 4
)

var Status_name = map[int32]string{
	0: "STATUS_UNSPECIFIED",
	1: "ACTIVE",
	2: "REQUIRED",
	3: "DISABLED",
	4: "HIDDEN",
}

var Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"ACTIVE":             1,
	"REQUIRED":           2,
	"DISABLED":           3,
	"HIDDEN":             4,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{0}
}

type SelectType int32

const (
	SelectType_SELECT_TYPE_UNSPECIFIED SelectType = 0
	SelectType_SIMPLE                  SelectType = 1
	SelectType_MULTI                   SelectType = 2
)

var SelectType_name = map[int32]string{
	0: "SELECT_TYPE_UNSPECIFIED",
	1: "SIMPLE",
	2: "MULTI",
}

var SelectType_value = map[string]int32{
	"SELECT_TYPE_UNSPECIFIED": 0,
	"SIMPLE":                  1,
	"MULTI":                   2,
}

func (x SelectType) String() string {
	return proto.EnumName(SelectType_name, int32(x))
}

func (SelectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{1}
}

type ButtonFuncType int32

const (
	ButtonFuncType_BUTTON_FUNC_UNSPECIFIED ButtonFuncType = 0
	ButtonFuncType_VALIDATE                ButtonFuncType = 1
	ButtonFuncType_RESET                   ButtonFuncType = 2
	ButtonFuncType_SEND                    ButtonFuncType = 3
)

var ButtonFuncType_name = map[int32]string{
	0: "BUTTON_FUNC_UNSPECIFIED",
	1: "VALIDATE",
	2: "RESET",
	3: "SEND",
}

var ButtonFuncType_value = map[string]int32{
	"BUTTON_FUNC_UNSPECIFIED": 0,
	"VALIDATE":                1,
	"RESET":                   2,
	"SEND":                    3,
}

func (x ButtonFuncType) String() string {
	return proto.EnumName(ButtonFuncType_name, int32(x))
}

func (ButtonFuncType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{2}
}

type GetFormRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFormRequest) Reset()         { *m = GetFormRequest{} }
func (m *GetFormRequest) String() string { return proto.CompactTextString(m) }
func (*GetFormRequest) ProtoMessage()    {}
func (*GetFormRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{0}
}

func (m *GetFormRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFormRequest.Unmarshal(m, b)
}
func (m *GetFormRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFormRequest.Marshal(b, m, deterministic)
}
func (m *GetFormRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFormRequest.Merge(m, src)
}
func (m *GetFormRequest) XXX_Size() int {
	return xxx_messageInfo_GetFormRequest.Size(m)
}
func (m *GetFormRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFormRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFormRequest proto.InternalMessageInfo

func (m *GetFormRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SendFormResponse struct {
	Form                 *Form    `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	Succeed              bool     `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendFormResponse) Reset()         { *m = SendFormResponse{} }
func (m *SendFormResponse) String() string { return proto.CompactTextString(m) }
func (*SendFormResponse) ProtoMessage()    {}
func (*SendFormResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{1}
}

func (m *SendFormResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendFormResponse.Unmarshal(m, b)
}
func (m *SendFormResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendFormResponse.Marshal(b, m, deterministic)
}
func (m *SendFormResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendFormResponse.Merge(m, src)
}
func (m *SendFormResponse) XXX_Size() int {
	return xxx_messageInfo_SendFormResponse.Size(m)
}
func (m *SendFormResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendFormResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendFormResponse proto.InternalMessageInfo

func (m *SendFormResponse) GetForm() *Form {
	if m != nil {
		return m.Form
	}
	return nil
}

func (m *SendFormResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func (m *SendFormResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Form struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields               []*Field  `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Buttons              []*Button `protobuf:"bytes,3,rep,name=buttons,proto3" json:"buttons,omitempty"`
	Valid                bool      `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Form) Reset()         { *m = Form{} }
func (m *Form) String() string { return proto.CompactTextString(m) }
func (*Form) ProtoMessage()    {}
func (*Form) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{2}
}

func (m *Form) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Form.Unmarshal(m, b)
}
func (m *Form) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Form.Marshal(b, m, deterministic)
}
func (m *Form) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Form.Merge(m, src)
}
func (m *Form) XXX_Size() int {
	return xxx_messageInfo_Form.Size(m)
}
func (m *Form) XXX_DiscardUnknown() {
	xxx_messageInfo_Form.DiscardUnknown(m)
}

var xxx_messageInfo_Form proto.InternalMessageInfo

func (m *Form) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Form) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Form) GetButtons() []*Button {
	if m != nil {
		return m.Buttons
	}
	return nil
}

func (m *Form) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type Field struct {
	Label                string        `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Status               Status        `protobuf:"varint,2,opt,name=status,proto3,enum=grpcform.Status" json:"status,omitempty"`
	InstantValidate      bool          `protobuf:"varint,3,opt,name=instant_validate,json=instantValidate,proto3" json:"instant_validate,omitempty"`
	Error                string        `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	TextField            *TextField    `protobuf:"bytes,10,opt,name=text_field,json=textField,proto3" json:"text_field,omitempty"`
	SelectField          *SelectField  `protobuf:"bytes,11,opt,name=select_field,json=selectField,proto3" json:"select_field,omitempty"`
	NumericField         *NumericField `protobuf:"bytes,12,opt,name=numeric_field,json=numericField,proto3" json:"numeric_field,omitempty"`
	ActiveIf             *ActiveIf     `protobuf:"bytes,20,opt,name=activeIf,proto3" json:"activeIf,omitempty"`
	RequiredIf           *RequiredIf   `protobuf:"bytes,21,opt,name=required_if,json=requiredIf,proto3" json:"required_if,omitempty"`
	DisabledIf           *DisabledIf   `protobuf:"bytes,22,opt,name=disabled_if,json=disabledIf,proto3" json:"disabled_if,omitempty"`
	HiddenIf             *HiddenIf     `protobuf:"bytes,23,opt,name=hidden_if,json=hiddenIf,proto3" json:"hidden_if,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{3}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Field) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (m *Field) GetInstantValidate() bool {
	if m != nil {
		return m.InstantValidate
	}
	return false
}

func (m *Field) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Field) GetTextField() *TextField {
	if m != nil {
		return m.TextField
	}
	return nil
}

func (m *Field) GetSelectField() *SelectField {
	if m != nil {
		return m.SelectField
	}
	return nil
}

func (m *Field) GetNumericField() *NumericField {
	if m != nil {
		return m.NumericField
	}
	return nil
}

func (m *Field) GetActiveIf() *ActiveIf {
	if m != nil {
		return m.ActiveIf
	}
	return nil
}

func (m *Field) GetRequiredIf() *RequiredIf {
	if m != nil {
		return m.RequiredIf
	}
	return nil
}

func (m *Field) GetDisabledIf() *DisabledIf {
	if m != nil {
		return m.DisabledIf
	}
	return nil
}

func (m *Field) GetHiddenIf() *HiddenIf {
	if m != nil {
		return m.HiddenIf
	}
	return nil
}

type ActiveIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ActiveIf) Reset()         { *m = ActiveIf{} }
func (m *ActiveIf) String() string { return proto.CompactTextString(m) }
func (*ActiveIf) ProtoMessage()    {}
func (*ActiveIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{4}
}

func (m *ActiveIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveIf.Unmarshal(m, b)
}
func (m *ActiveIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveIf.Marshal(b, m, deterministic)
}
func (m *ActiveIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveIf.Merge(m, src)
}
func (m *ActiveIf) XXX_Size() int {
	return xxx_messageInfo_ActiveIf.Size(m)
}
func (m *ActiveIf) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveIf.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveIf proto.InternalMessageInfo

func (m *ActiveIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type RequiredIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RequiredIf) Reset()         { *m = RequiredIf{} }
func (m *RequiredIf) String() string { return proto.CompactTextString(m) }
func (*RequiredIf) ProtoMessage()    {}
func (*RequiredIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{5}
}

func (m *RequiredIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequiredIf.Unmarshal(m, b)
}
func (m *RequiredIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequiredIf.Marshal(b, m, deterministic)
}
func (m *RequiredIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequiredIf.Merge(m, src)
}
func (m *RequiredIf) XXX_Size() int {
	return xxx_messageInfo_RequiredIf.Size(m)
}
func (m *RequiredIf) XXX_DiscardUnknown() {
	xxx_messageInfo_RequiredIf.DiscardUnknown(m)
}

var xxx_messageInfo_RequiredIf proto.InternalMessageInfo

func (m *RequiredIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type DisabledIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DisabledIf) Reset()         { *m = DisabledIf{} }
func (m *DisabledIf) String() string { return proto.CompactTextString(m) }
func (*DisabledIf) ProtoMessage()    {}
func (*DisabledIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{6}
}

func (m *DisabledIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisabledIf.Unmarshal(m, b)
}
func (m *DisabledIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisabledIf.Marshal(b, m, deterministic)
}
func (m *DisabledIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisabledIf.Merge(m, src)
}
func (m *DisabledIf) XXX_Size() int {
	return xxx_messageInfo_DisabledIf.Size(m)
}
func (m *DisabledIf) XXX_DiscardUnknown() {
	xxx_messageInfo_DisabledIf.DiscardUnknown(m)
}

var xxx_messageInfo_DisabledIf proto.InternalMessageInfo

func (m *DisabledIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type HiddenIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HiddenIf) Reset()         { *m = HiddenIf{} }
func (m *HiddenIf) String() string { return proto.CompactTextString(m) }
func (*HiddenIf) ProtoMessage()    {}
func (*HiddenIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{7}
}

func (m *HiddenIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiddenIf.Unmarshal(m, b)
}
func (m *HiddenIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiddenIf.Marshal(b, m, deterministic)
}
func (m *HiddenIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiddenIf.Merge(m, src)
}
func (m *HiddenIf) XXX_Size() int {
	return xxx_messageInfo_HiddenIf.Size(m)
}
func (m *HiddenIf) XXX_DiscardUnknown() {
	xxx_messageInfo_HiddenIf.DiscardUnknown(m)
}

var xxx_messageInfo_HiddenIf proto.InternalMessageInfo

func (m *HiddenIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type Validator struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	EqualText            string   `protobuf:"bytes,10,opt,name=equal_text,json=equalText,proto3" json:"equal_text,omitempty"`
	SmallerThanLength    int64    `protobuf:"varint,11,opt,name=smaller_than_length,json=smallerThanLength,proto3" json:"smaller_than_length,omitempty"`
	GreterThanLength     int64    `protobuf:"varint,12,opt,name=greter_than_length,json=greterThanLength,proto3" json:"greter_than_length,omitempty"`
	EqualNumber          int64    `protobuf:"varint,20,opt,name=equal_number,json=equalNumber,proto3" json:"equal_number,omitempty"`
	SmallerThanNumber    int64    `protobuf:"varint,21,opt,name=smaller_than_number,json=smallerThanNumber,proto3" json:"smaller_than_number,omitempty"`
	GreaterThanNumber    int64    `protobuf:"varint,22,opt,name=greater_than_number,json=greaterThanNumber,proto3" json:"greater_than_number,omitempty"`
	EqualOption          *Option  `protobuf:"bytes,30,opt,name=equal_option,json=equalOption,proto3" json:"equal_option,omitempty"`
	Regex                string   `protobuf:"bytes,40,opt,name=regex,proto3" json:"regex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{8}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Validator) GetEqualText() string {
	if m != nil {
		return m.EqualText
	}
	return ""
}

func (m *Validator) GetSmallerThanLength() int64 {
	if m != nil {
		return m.SmallerThanLength
	}
	return 0
}

func (m *Validator) GetGreterThanLength() int64 {
	if m != nil {
		return m.GreterThanLength
	}
	return 0
}

func (m *Validator) GetEqualNumber() int64 {
	if m != nil {
		return m.EqualNumber
	}
	return 0
}

func (m *Validator) GetSmallerThanNumber() int64 {
	if m != nil {
		return m.SmallerThanNumber
	}
	return 0
}

func (m *Validator) GetGreaterThanNumber() int64 {
	if m != nil {
		return m.GreaterThanNumber
	}
	return 0
}

func (m *Validator) GetEqualOption() *Option {
	if m != nil {
		return m.EqualOption
	}
	return nil
}

func (m *Validator) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

type TextField struct {
	Value                string    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Options              []*Option `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	Min                  int64     `protobuf:"varint,10,opt,name=min,proto3" json:"min,omitempty"`
	MinError             string    `protobuf:"bytes,20,opt,name=min_error,json=minError,proto3" json:"min_error,omitempty"`
	Max                  int64     `protobuf:"varint,11,opt,name=max,proto3" json:"max,omitempty"`
	MaxError             string    `protobuf:"bytes,21,opt,name=max_error,json=maxError,proto3" json:"max_error,omitempty"`
	Regex                string    `protobuf:"bytes,12,opt,name=regex,proto3" json:"regex,omitempty"`
	RegexError           string    `protobuf:"bytes,22,opt,name=regex_error,json=regexError,proto3" json:"regex_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TextField) Reset()         { *m = TextField{} }
func (m *TextField) String() string { return proto.CompactTextString(m) }
func (*TextField) ProtoMessage()    {}
func (*TextField) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{9}
}

func (m *TextField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextField.Unmarshal(m, b)
}
func (m *TextField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextField.Marshal(b, m, deterministic)
}
func (m *TextField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextField.Merge(m, src)
}
func (m *TextField) XXX_Size() int {
	return xxx_messageInfo_TextField.Size(m)
}
func (m *TextField) XXX_DiscardUnknown() {
	xxx_messageInfo_TextField.DiscardUnknown(m)
}

var xxx_messageInfo_TextField proto.InternalMessageInfo

func (m *TextField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TextField) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *TextField) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *TextField) GetMinError() string {
	if m != nil {
		return m.MinError
	}
	return ""
}

func (m *TextField) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *TextField) GetMaxError() string {
	if m != nil {
		return m.MaxError
	}
	return ""
}

func (m *TextField) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

func (m *TextField) GetRegexError() string {
	if m != nil {
		return m.RegexError
	}
	return ""
}

type SelectField struct {
	Option               *Option    `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Type                 SelectType `protobuf:"varint,2,opt,name=type,proto3,enum=grpcform.SelectType" json:"type,omitempty"`
	Options              []*Option  `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	Error                string     `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SelectField) Reset()         { *m = SelectField{} }
func (m *SelectField) String() string { return proto.CompactTextString(m) }
func (*SelectField) ProtoMessage()    {}
func (*SelectField) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{10}
}

func (m *SelectField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectField.Unmarshal(m, b)
}
func (m *SelectField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectField.Marshal(b, m, deterministic)
}
func (m *SelectField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectField.Merge(m, src)
}
func (m *SelectField) XXX_Size() int {
	return xxx_messageInfo_SelectField.Size(m)
}
func (m *SelectField) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectField.DiscardUnknown(m)
}

var xxx_messageInfo_SelectField proto.InternalMessageInfo

func (m *SelectField) GetOption() *Option {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *SelectField) GetType() SelectType {
	if m != nil {
		return m.Type
	}
	return SelectType_SELECT_TYPE_UNSPECIFIED
}

func (m *SelectField) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *SelectField) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type NumericField struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Step                 int64    `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Min                  int64    `protobuf:"varint,10,opt,name=min,proto3" json:"min,omitempty"`
	MinError             string   `protobuf:"bytes,20,opt,name=min_error,json=minError,proto3" json:"min_error,omitempty"`
	Max                  int64    `protobuf:"varint,11,opt,name=max,proto3" json:"max,omitempty"`
	MaxError             string   `protobuf:"bytes,21,opt,name=max_error,json=maxError,proto3" json:"max_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumericField) Reset()         { *m = NumericField{} }
func (m *NumericField) String() string { return proto.CompactTextString(m) }
func (*NumericField) ProtoMessage()    {}
func (*NumericField) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{11}
}

func (m *NumericField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumericField.Unmarshal(m, b)
}
func (m *NumericField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumericField.Marshal(b, m, deterministic)
}
func (m *NumericField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumericField.Merge(m, src)
}
func (m *NumericField) XXX_Size() int {
	return xxx_messageInfo_NumericField.Size(m)
}
func (m *NumericField) XXX_DiscardUnknown() {
	xxx_messageInfo_NumericField.DiscardUnknown(m)
}

var xxx_messageInfo_NumericField proto.InternalMessageInfo

func (m *NumericField) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NumericField) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *NumericField) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *NumericField) GetMinError() string {
	if m != nil {
		return m.MinError
	}
	return ""
}

func (m *NumericField) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *NumericField) GetMaxError() string {
	if m != nil {
		return m.MaxError
	}
	return ""
}

type Option struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{12}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Option) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Button struct {
	Label                string         `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Status               Status         `protobuf:"varint,2,opt,name=status,proto3,enum=grpcform.Status" json:"status,omitempty"`
	Type                 ButtonFuncType `protobuf:"varint,3,opt,name=type,proto3,enum=grpcform.ButtonFuncType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Button) Reset()         { *m = Button{} }
func (m *Button) String() string { return proto.CompactTextString(m) }
func (*Button) ProtoMessage()    {}
func (*Button) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{13}
}

func (m *Button) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Button.Unmarshal(m, b)
}
func (m *Button) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Button.Marshal(b, m, deterministic)
}
func (m *Button) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Button.Merge(m, src)
}
func (m *Button) XXX_Size() int {
	return xxx_messageInfo_Button.Size(m)
}
func (m *Button) XXX_DiscardUnknown() {
	xxx_messageInfo_Button.DiscardUnknown(m)
}

var xxx_messageInfo_Button proto.InternalMessageInfo

func (m *Button) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Button) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (m *Button) GetType() ButtonFuncType {
	if m != nil {
		return m.Type
	}
	return ButtonFuncType_BUTTON_FUNC_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("grpcform.Status", Status_name, Status_value)
	proto.RegisterEnum("grpcform.SelectType", SelectType_name, SelectType_value)
	proto.RegisterEnum("grpcform.ButtonFuncType", ButtonFuncType_name, ButtonFuncType_value)
	proto.RegisterType((*GetFormRequest)(nil), "grpcform.GetFormRequest")
	proto.RegisterType((*SendFormResponse)(nil), "grpcform.SendFormResponse")
	proto.RegisterType((*Form)(nil), "grpcform.Form")
	proto.RegisterType((*Field)(nil), "grpcform.Field")
	proto.RegisterType((*ActiveIf)(nil), "grpcform.ActiveIf")
	proto.RegisterType((*RequiredIf)(nil), "grpcform.RequiredIf")
	proto.RegisterType((*DisabledIf)(nil), "grpcform.DisabledIf")
	proto.RegisterType((*HiddenIf)(nil), "grpcform.HiddenIf")
	proto.RegisterType((*Validator)(nil), "grpcform.Validator")
	proto.RegisterType((*TextField)(nil), "grpcform.TextField")
	proto.RegisterType((*SelectField)(nil), "grpcform.SelectField")
	proto.RegisterType((*NumericField)(nil), "grpcform.NumericField")
	proto.RegisterType((*Option)(nil), "grpcform.Option")
	proto.RegisterType((*Button)(nil), "grpcform.Button")
}

func init() { proto.RegisterFile("grpc-form.proto", fileDescriptor_875c494c6e4805a2) }

var fileDescriptor_875c494c6e4805a2 = []byte{
	// 1056 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xe1, 0x6e, 0xe3, 0x44,
	0x10, 0xae, 0xe3, 0x34, 0x75, 0x26, 0xa1, 0x35, 0x7b, 0x6d, 0xcf, 0xba, 0x13, 0x50, 0x2c, 0x24,
	0x42, 0x75, 0x14, 0xd4, 0x72, 0xd2, 0x49, 0xfc, 0x38, 0xd2, 0xc6, 0xe5, 0x2c, 0xe5, 0x72, 0x65,
	0xed, 0x54, 0x82, 0x3f, 0x91, 0x9b, 0x6c, 0x53, 0xa3, 0xd8, 0x4e, 0xed, 0x75, 0x95, 0xfb, 0x8b,
	0xc4, 0x2b, 0xf0, 0x02, 0xbc, 0x00, 0xcf, 0xc4, 0x6f, 0x1e, 0x02, 0xed, 0xec, 0x3a, 0x76, 0x93,
	0x22, 0xa4, 0x22, 0xfe, 0xed, 0xcc, 0xf7, 0x7d, 0xb3, 0xb3, 0xbb, 0xe3, 0xf1, 0xc0, 0xce, 0x34,
	0x9d, 0x8f, 0xbf, 0xbc, 0x4e, 0xd2, 0xe8, 0x68, 0x9e, 0x26, 0x3c, 0x21, 0x86, 0x70, 0x08, 0xdb,
	0xfe, 0x0c, 0xb6, 0xbf, 0x67, 0xfc, 0x3c, 0x49, 0x23, 0xca, 0x6e, 0x73, 0x96, 0x71, 0x42, 0xa0,
	0x1e, 0x07, 0x11, 0xb3, 0xb4, 0x03, 0xad, 0xd3, 0xa4, 0xb8, 0xb6, 0x7f, 0x06, 0xd3, 0x63, 0xf1,
	0x44, 0xd2, 0xb2, 0x79, 0x12, 0x67, 0x8c, 0xd8, 0x50, 0x17, 0x11, 0x90, 0xd7, 0x3a, 0xde, 0x3e,
	0x2a, 0x42, 0x1e, 0x21, 0x0b, 0x31, 0x62, 0xc1, 0x56, 0x96, 0x8f, 0xc7, 0x8c, 0x4d, 0xac, 0xda,
	0x81, 0xd6, 0x31, 0x68, 0x61, 0x0a, 0x24, 0x62, 0x59, 0x16, 0x4c, 0x99, 0xa5, 0xe3, 0x46, 0x85,
	0x69, 0xff, 0xaa, 0x41, 0x5d, 0x84, 0x78, 0x28, 0x11, 0xf2, 0x39, 0x34, 0xae, 0x43, 0x36, 0x9b,
	0x64, 0x56, 0xed, 0x40, 0xef, 0xb4, 0x8e, 0x77, 0x2a, 0xdb, 0x0a, 0x3f, 0x55, 0x30, 0x39, 0x84,
	0xad, 0xab, 0x9c, 0xf3, 0x24, 0xce, 0x2c, 0x1d, 0x99, 0x66, 0xc9, 0x3c, 0x45, 0x80, 0x16, 0x04,
	0xb2, 0x0b, 0x9b, 0x77, 0xc1, 0x2c, 0x9c, 0x58, 0x75, 0xcc, 0x51, 0x1a, 0xf6, 0x2f, 0x75, 0xd8,
	0xc4, 0x98, 0x02, 0x9f, 0x05, 0x57, 0x6c, 0xa6, 0x32, 0x91, 0x06, 0xe9, 0x40, 0x23, 0xe3, 0x01,
	0xcf, 0x33, 0x3c, 0xda, 0x76, 0x75, 0x03, 0x0f, 0xfd, 0x54, 0xe1, 0xe4, 0x0b, 0x30, 0xc3, 0x38,
	0xe3, 0x41, 0xcc, 0x47, 0x18, 0x3a, 0xe0, 0xf2, 0xd0, 0x06, 0xdd, 0x51, 0xfe, 0x4b, 0xe5, 0x16,
	0x5b, 0xb1, 0x34, 0x4d, 0x52, 0x4c, 0xa5, 0x49, 0xa5, 0x41, 0x8e, 0x01, 0x38, 0x5b, 0xf0, 0x11,
	0x9e, 0xcd, 0x02, 0xbc, 0xf0, 0x27, 0xe5, 0x76, 0x3e, 0x5b, 0x70, 0x79, 0xfa, 0x26, 0x2f, 0x96,
	0xe4, 0x15, 0xb4, 0x33, 0x36, 0x63, 0xe3, 0x42, 0xd5, 0x42, 0xd5, 0x5e, 0x25, 0x49, 0x44, 0xa5,
	0xae, 0x95, 0x95, 0x06, 0xf9, 0x16, 0x3e, 0x88, 0xf3, 0x88, 0xa5, 0xe1, 0x58, 0x49, 0xdb, 0x28,
	0xdd, 0x2f, 0xa5, 0x03, 0x09, 0x4b, 0x6d, 0x3b, 0xae, 0x58, 0xe4, 0x08, 0x8c, 0x60, 0xcc, 0xc3,
	0x3b, 0xe6, 0x5e, 0x5b, 0xbb, 0xa8, 0x23, 0xa5, 0xae, 0xab, 0x10, 0xba, 0xe4, 0x90, 0x97, 0xd0,
	0x4a, 0xd9, 0x6d, 0x1e, 0xa6, 0x6c, 0x32, 0x0a, 0xaf, 0xad, 0x3d, 0x94, 0xec, 0x96, 0x12, 0xaa,
	0x40, 0xf7, 0x9a, 0x42, 0xba, 0x5c, 0x0b, 0xd9, 0x24, 0xcc, 0x82, 0xab, 0x99, 0x94, 0xed, 0xaf,
	0xca, 0x7a, 0x0a, 0x14, 0xb2, 0xc9, 0x72, 0x4d, 0xbe, 0x82, 0xe6, 0x4d, 0x38, 0x99, 0xb0, 0x58,
	0x88, 0x9e, 0xae, 0xa6, 0xf7, 0x06, 0x21, 0x91, 0xde, 0x8d, 0x5a, 0xd9, 0xaf, 0xc1, 0x28, 0x92,
	0x26, 0x27, 0x00, 0xea, 0xf9, 0x92, 0x34, 0xb3, 0x34, 0xac, 0xaa, 0xca, 0x2b, 0x5c, 0x16, 0x18,
	0xad, 0xd0, 0xec, 0x2e, 0x40, 0x79, 0x84, 0x47, 0x87, 0x28, 0x8f, 0xf3, 0xb8, 0x10, 0xaf, 0xc1,
	0x28, 0x0e, 0xf7, 0xb8, 0x00, 0x7f, 0xd5, 0xa0, 0xb9, 0x44, 0x44, 0x95, 0x86, 0xf1, 0x84, 0x2d,
	0xf0, 0x83, 0xd0, 0xa9, 0x34, 0xc8, 0x47, 0x00, 0xec, 0x36, 0x0f, 0x66, 0x23, 0x51, 0x84, 0x58,
	0xa5, 0x4d, 0xda, 0x44, 0x8f, 0x28, 0x50, 0x72, 0x04, 0x4f, 0xb2, 0x28, 0x98, 0xcd, 0x58, 0x3a,
	0xe2, 0x37, 0x41, 0x3c, 0x9a, 0xb1, 0x78, 0xca, 0x6f, 0xb0, 0x2e, 0x75, 0xfa, 0xa1, 0x82, 0xfc,
	0x9b, 0x20, 0xee, 0x23, 0x40, 0x5e, 0x00, 0x99, 0xa6, 0x8c, 0xaf, 0xd0, 0xdb, 0x48, 0x37, 0x25,
	0x52, 0x61, 0x7f, 0x0a, 0x6d, 0xb9, 0x79, 0x9c, 0x47, 0x57, 0x2c, 0xc5, 0xda, 0xd3, 0x69, 0x0b,
	0x7d, 0x03, 0x74, 0xad, 0x25, 0xa0, 0x98, 0x7b, 0x6b, 0x09, 0x94, 0xfc, 0x69, 0xca, 0x02, 0xbe,
	0xc2, 0xdf, 0x97, 0x7c, 0x05, 0x55, 0xf8, 0x27, 0x45, 0x0a, 0xc9, 0x9c, 0x87, 0x49, 0x6c, 0x7d,
	0x8c, 0xf5, 0x55, 0x69, 0x0b, 0xef, 0xd0, 0xaf, 0x92, 0x92, 0x86, 0xb8, 0xca, 0x94, 0x4d, 0xd9,
	0xc2, 0xea, 0xc8, 0x0f, 0x1e, 0x0d, 0xfb, 0x4f, 0x0d, 0x9a, 0xcb, 0xaf, 0x5a, 0xf5, 0xa7, 0xbc,
	0xe8, 0x84, 0xd2, 0x10, 0x1d, 0x4e, 0x6e, 0x54, 0xf4, 0xc2, 0xf5, 0x9d, 0x0a, 0x02, 0x31, 0x41,
	0x8f, 0xc2, 0x18, 0xdf, 0x44, 0xa7, 0x62, 0x49, 0x9e, 0x43, 0x33, 0x0a, 0xe3, 0x91, 0x6c, 0x36,
	0xbb, 0x18, 0xd7, 0x88, 0xc2, 0xd8, 0xc1, 0x7e, 0x23, 0xe8, 0xc1, 0x42, 0x3d, 0x8d, 0x58, 0x22,
	0x3d, 0x58, 0x28, 0xfa, 0x9e, 0xa2, 0x07, 0x0b, 0x49, 0x5f, 0x9e, 0xa1, 0x5d, 0x39, 0x03, 0xf9,
	0x44, 0x7c, 0xd9, 0x53, 0x56, 0x88, 0xf6, 0x11, 0x03, 0x74, 0xa1, 0xcc, 0xfe, 0x5d, 0x83, 0x56,
	0xa5, 0x09, 0x89, 0x86, 0xaa, 0x6e, 0x4e, 0xfb, 0x87, 0x9b, 0x53, 0x38, 0xe9, 0x40, 0x9d, 0xbf,
	0x9f, 0x33, 0xd5, 0x78, 0x77, 0x57, 0x7b, 0x9a, 0xff, 0x7e, 0xce, 0x28, 0x32, 0xaa, 0x97, 0xa4,
	0xff, 0xdb, 0x25, 0x3d, 0xd8, 0x7b, 0xed, 0xdf, 0x34, 0x68, 0x57, 0xfb, 0xdd, 0xfd, 0xd7, 0xd0,
	0x8b, 0xd7, 0x20, 0x50, 0xcf, 0x38, 0x9b, 0x63, 0x4a, 0x3a, 0xc5, 0xf5, 0xff, 0x7b, 0xeb, 0xf6,
	0x37, 0xd0, 0x28, 0x6b, 0xe8, 0x81, 0xcf, 0x71, 0x99, 0x67, 0xad, 0x52, 0x35, 0xf6, 0x1d, 0x34,
	0xe4, 0xef, 0xef, 0x3f, 0xff, 0xd5, 0x5e, 0xa8, 0x47, 0xd0, 0x91, 0x67, 0xad, 0xfe, 0x5e, 0xcf,
	0xf3, 0x78, 0x5c, 0x3e, 0xc4, 0xa1, 0x0f, 0x0d, 0xa9, 0x27, 0xfb, 0x40, 0x3c, 0xbf, 0xeb, 0x0f,
	0xbd, 0xd1, 0x70, 0xe0, 0x5d, 0x38, 0x67, 0xee, 0xb9, 0xeb, 0xf4, 0xcc, 0x0d, 0x02, 0xd0, 0xe8,
	0x9e, 0xf9, 0xee, 0xa5, 0x63, 0x6a, 0xa4, 0x0d, 0x06, 0x75, 0x7e, 0x18, 0xba, 0xd4, 0xe9, 0x99,
	0x35, 0x61, 0xf5, 0x5c, 0xaf, 0x7b, 0xda, 0x77, 0x7a, 0xa6, 0x2e, 0x78, 0x6f, 0xdc, 0x5e, 0xcf,
	0x19, 0x98, 0xf5, 0xc3, 0xef, 0x00, 0xca, 0x27, 0x27, 0xcf, 0xe1, 0xa9, 0xe7, 0xf4, 0x9d, 0x33,
	0x7f, 0xe4, 0xff, 0x78, 0xe1, 0xac, 0x87, 0xf7, 0xdc, 0xb7, 0x17, 0x7d, 0x11, 0xbe, 0x09, 0x9b,
	0x6f, 0x87, 0x7d, 0xdf, 0x35, 0x6b, 0x87, 0x17, 0xb0, 0x7d, 0x3f, 0x5f, 0x11, 0xe5, 0x74, 0xe8,
	0xfb, 0xef, 0x06, 0xa3, 0xf3, 0xe1, 0xe0, 0x6c, 0x25, 0x4a, 0x1b, 0x8c, 0xcb, 0x6e, 0xdf, 0xed,
	0x75, 0x7d, 0x15, 0x87, 0x3a, 0x9e, 0xe3, 0x9b, 0x35, 0x62, 0x40, 0xdd, 0x73, 0x06, 0x3d, 0x53,
	0x3f, 0xfe, 0x43, 0x83, 0x96, 0x98, 0x5f, 0x3c, 0x96, 0xde, 0x85, 0x63, 0x46, 0x5e, 0xc2, 0x96,
	0x9a, 0xb0, 0x48, 0xe5, 0x92, 0xee, 0x0f, 0x5d, 0xcf, 0x56, 0xc6, 0x27, 0x7b, 0x83, 0x7c, 0x0d,
	0xed, 0x62, 0x2a, 0x40, 0xed, 0x0a, 0xe3, 0x01, 0xc5, 0x2b, 0x30, 0x8a, 0x21, 0x6d, 0x8d, 0xfd,
	0xac, 0xfa, 0x8d, 0xdc, 0x1f, 0xe4, 0xec, 0x8d, 0x53, 0xf8, 0x69, 0x39, 0x10, 0x5e, 0x35, 0x70,
	0x42, 0x3c, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x56, 0x48, 0xae, 0x62, 0x34, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FormServiceClient is the client API for FormService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FormServiceClient interface {
	GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*Form, error)
	ValidateForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*Form, error)
	SendForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*SendFormResponse, error)
}

type formServiceClient struct {
	cc *grpc.ClientConn
}

func NewFormServiceClient(cc *grpc.ClientConn) FormServiceClient {
	return &formServiceClient{cc}
}

func (c *formServiceClient) GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*Form, error) {
	out := new(Form)
	err := c.cc.Invoke(ctx, "/grpcform.FormService/GetForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) ValidateForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*Form, error) {
	out := new(Form)
	err := c.cc.Invoke(ctx, "/grpcform.FormService/ValidateForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) SendForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*SendFormResponse, error) {
	out := new(SendFormResponse)
	err := c.cc.Invoke(ctx, "/grpcform.FormService/SendForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormServiceServer is the server API for FormService service.
type FormServiceServer interface {
	GetForm(context.Context, *GetFormRequest) (*Form, error)
	ValidateForm(context.Context, *Form) (*Form, error)
	SendForm(context.Context, *Form) (*SendFormResponse, error)
}

func RegisterFormServiceServer(s *grpc.Server, srv FormServiceServer) {
	s.RegisterService(&_FormService_serviceDesc, srv)
}

func _FormService_GetForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).GetForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcform.FormService/GetForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormServiceServer).GetForm(ctx, req.(*GetFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_ValidateForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Form)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).ValidateForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcform.FormService/ValidateForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormServiceServer).ValidateForm(ctx, req.(*Form))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_SendForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Form)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).SendForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcform.FormService/SendForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormServiceServer).SendForm(ctx, req.(*Form))
	}
	return interceptor(ctx, in, info, handler)
}

var _FormService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcform.FormService",
	HandlerType: (*FormServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetForm",
			Handler:    _FormService_GetForm_Handler,
		},
		{
			MethodName: "ValidateForm",
			Handler:    _FormService_ValidateForm_Handler,
		},
		{
			MethodName: "SendForm",
			Handler:    _FormService_SendForm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-form.proto",
}
