// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-form.proto

package grpcform

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldStatus int32

const (
	FieldStatus_FIELD_STATUS_UNSPECIFIED FieldStatus = 0
	FieldStatus_FIELD_STATUS_ACTIVE      FieldStatus = 1
	FieldStatus_FIELD_STATUS_REQUIRED    FieldStatus = 2
	FieldStatus_FIELD_STATUS_DISABLED    FieldStatus = 3
	FieldStatus_FIELD_STATUS_HIDDEN      FieldStatus = 4
)

var FieldStatus_name = map[int32]string{
	0: "FIELD_STATUS_UNSPECIFIED",
	1: "FIELD_STATUS_ACTIVE",
	2: "FIELD_STATUS_REQUIRED",
	3: "FIELD_STATUS_DISABLED",
	4: "FIELD_STATUS_HIDDEN",
}

var FieldStatus_value = map[string]int32{
	"FIELD_STATUS_UNSPECIFIED": 0,
	"FIELD_STATUS_ACTIVE":      1,
	"FIELD_STATUS_REQUIRED":    2,
	"FIELD_STATUS_DISABLED":    3,
	"FIELD_STATUS_HIDDEN":      4,
}

func (x FieldStatus) String() string {
	return proto.EnumName(FieldStatus_name, int32(x))
}

func (FieldStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{0}
}

type SelectType int32

const (
	SelectType_SELECT_TYPE_UNSPECIFIED SelectType = 0
	SelectType_SELECT_TYPE_SIMPLE      SelectType = 1
	SelectType_SELECT_TYPE_MULTI       SelectType = 2
)

var SelectType_name = map[int32]string{
	0: "SELECT_TYPE_UNSPECIFIED",
	1: "SELECT_TYPE_SIMPLE",
	2: "SELECT_TYPE_MULTI",
}

var SelectType_value = map[string]int32{
	"SELECT_TYPE_UNSPECIFIED": 0,
	"SELECT_TYPE_SIMPLE":      1,
	"SELECT_TYPE_MULTI":       2,
}

func (x SelectType) String() string {
	return proto.EnumName(SelectType_name, int32(x))
}

func (SelectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{1}
}

type ButtonStatus int32

const (
	ButtonStatus_BUTTON_STATUS_UNSPECIFIED ButtonStatus = 0
	ButtonStatus_BUTTON_ACTIVE             ButtonStatus = 1
	ButtonStatus_BUTTON_DISABLED           ButtonStatus = 3
	ButtonStatus_BUTTON_HIDDEN             ButtonStatus = 4
)

var ButtonStatus_name = map[int32]string{
	0: "BUTTON_STATUS_UNSPECIFIED",
	1: "BUTTON_ACTIVE",
	3: "BUTTON_DISABLED",
	4: "BUTTON_HIDDEN",
}

var ButtonStatus_value = map[string]int32{
	"BUTTON_STATUS_UNSPECIFIED": 0,
	"BUTTON_ACTIVE":             1,
	"BUTTON_DISABLED":           3,
	"BUTTON_HIDDEN":             4,
}

func (x ButtonStatus) String() string {
	return proto.EnumName(ButtonStatus_name, int32(x))
}

func (ButtonStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{2}
}

type ButtonFuncType int32

const (
	ButtonFuncType_BUTTON_FUNC_UNSPECIFIED ButtonFuncType = 0
	ButtonFuncType_BUTTON_FUNC_VALIDATE    ButtonFuncType = 1
	ButtonFuncType_BUTTON_FUNC_RESET       ButtonFuncType = 2
	ButtonFuncType_BUTTON_FUNC_SEND        ButtonFuncType = 3
)

var ButtonFuncType_name = map[int32]string{
	0: "BUTTON_FUNC_UNSPECIFIED",
	1: "BUTTON_FUNC_VALIDATE",
	2: "BUTTON_FUNC_RESET",
	3: "BUTTON_FUNC_SEND",
}

var ButtonFuncType_value = map[string]int32{
	"BUTTON_FUNC_UNSPECIFIED": 0,
	"BUTTON_FUNC_VALIDATE":    1,
	"BUTTON_FUNC_RESET":       2,
	"BUTTON_FUNC_SEND":        3,
}

func (x ButtonFuncType) String() string {
	return proto.EnumName(ButtonFuncType_name, int32(x))
}

func (ButtonFuncType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{3}
}

type GetFormRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFormRequest) Reset()         { *m = GetFormRequest{} }
func (m *GetFormRequest) String() string { return proto.CompactTextString(m) }
func (*GetFormRequest) ProtoMessage()    {}
func (*GetFormRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{0}
}

func (m *GetFormRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFormRequest.Unmarshal(m, b)
}
func (m *GetFormRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFormRequest.Marshal(b, m, deterministic)
}
func (m *GetFormRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFormRequest.Merge(m, src)
}
func (m *GetFormRequest) XXX_Size() int {
	return xxx_messageInfo_GetFormRequest.Size(m)
}
func (m *GetFormRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFormRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFormRequest proto.InternalMessageInfo

func (m *GetFormRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SendFormResponse struct {
	Form                 *Form    `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	Succeed              bool     `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendFormResponse) Reset()         { *m = SendFormResponse{} }
func (m *SendFormResponse) String() string { return proto.CompactTextString(m) }
func (*SendFormResponse) ProtoMessage()    {}
func (*SendFormResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{1}
}

func (m *SendFormResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendFormResponse.Unmarshal(m, b)
}
func (m *SendFormResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendFormResponse.Marshal(b, m, deterministic)
}
func (m *SendFormResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendFormResponse.Merge(m, src)
}
func (m *SendFormResponse) XXX_Size() int {
	return xxx_messageInfo_SendFormResponse.Size(m)
}
func (m *SendFormResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendFormResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendFormResponse proto.InternalMessageInfo

func (m *SendFormResponse) GetForm() *Form {
	if m != nil {
		return m.Form
	}
	return nil
}

func (m *SendFormResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func (m *SendFormResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Form struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields               []*Field  `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Buttons              []*Button `protobuf:"bytes,3,rep,name=buttons,proto3" json:"buttons,omitempty"`
	Valid                bool      `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Form) Reset()         { *m = Form{} }
func (m *Form) String() string { return proto.CompactTextString(m) }
func (*Form) ProtoMessage()    {}
func (*Form) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{2}
}

func (m *Form) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Form.Unmarshal(m, b)
}
func (m *Form) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Form.Marshal(b, m, deterministic)
}
func (m *Form) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Form.Merge(m, src)
}
func (m *Form) XXX_Size() int {
	return xxx_messageInfo_Form.Size(m)
}
func (m *Form) XXX_DiscardUnknown() {
	xxx_messageInfo_Form.DiscardUnknown(m)
}

var xxx_messageInfo_Form proto.InternalMessageInfo

func (m *Form) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Form) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Form) GetButtons() []*Button {
	if m != nil {
		return m.Buttons
	}
	return nil
}

func (m *Form) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type Field struct {
	Label                string        `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Status               FieldStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=grpcform.FieldStatus" json:"status,omitempty"`
	InstantValidate      bool          `protobuf:"varint,3,opt,name=instant_validate,json=instantValidate,proto3" json:"instant_validate,omitempty"`
	Error                string        `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	TextField            *TextField    `protobuf:"bytes,10,opt,name=text_field,json=textField,proto3" json:"text_field,omitempty"`
	SelectField          *SelectField  `protobuf:"bytes,11,opt,name=select_field,json=selectField,proto3" json:"select_field,omitempty"`
	NumericField         *NumericField `protobuf:"bytes,12,opt,name=numeric_field,json=numericField,proto3" json:"numeric_field,omitempty"`
	ActiveIf             *ActiveIf     `protobuf:"bytes,20,opt,name=activeIf,proto3" json:"activeIf,omitempty"`
	RequiredIf           *RequiredIf   `protobuf:"bytes,21,opt,name=required_if,json=requiredIf,proto3" json:"required_if,omitempty"`
	DisabledIf           *DisabledIf   `protobuf:"bytes,22,opt,name=disabled_if,json=disabledIf,proto3" json:"disabled_if,omitempty"`
	HiddenIf             *HiddenIf     `protobuf:"bytes,23,opt,name=hidden_if,json=hiddenIf,proto3" json:"hidden_if,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{3}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Field) GetStatus() FieldStatus {
	if m != nil {
		return m.Status
	}
	return FieldStatus_FIELD_STATUS_UNSPECIFIED
}

func (m *Field) GetInstantValidate() bool {
	if m != nil {
		return m.InstantValidate
	}
	return false
}

func (m *Field) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Field) GetTextField() *TextField {
	if m != nil {
		return m.TextField
	}
	return nil
}

func (m *Field) GetSelectField() *SelectField {
	if m != nil {
		return m.SelectField
	}
	return nil
}

func (m *Field) GetNumericField() *NumericField {
	if m != nil {
		return m.NumericField
	}
	return nil
}

func (m *Field) GetActiveIf() *ActiveIf {
	if m != nil {
		return m.ActiveIf
	}
	return nil
}

func (m *Field) GetRequiredIf() *RequiredIf {
	if m != nil {
		return m.RequiredIf
	}
	return nil
}

func (m *Field) GetDisabledIf() *DisabledIf {
	if m != nil {
		return m.DisabledIf
	}
	return nil
}

func (m *Field) GetHiddenIf() *HiddenIf {
	if m != nil {
		return m.HiddenIf
	}
	return nil
}

type ActiveIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ActiveIf) Reset()         { *m = ActiveIf{} }
func (m *ActiveIf) String() string { return proto.CompactTextString(m) }
func (*ActiveIf) ProtoMessage()    {}
func (*ActiveIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{4}
}

func (m *ActiveIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveIf.Unmarshal(m, b)
}
func (m *ActiveIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveIf.Marshal(b, m, deterministic)
}
func (m *ActiveIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveIf.Merge(m, src)
}
func (m *ActiveIf) XXX_Size() int {
	return xxx_messageInfo_ActiveIf.Size(m)
}
func (m *ActiveIf) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveIf.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveIf proto.InternalMessageInfo

func (m *ActiveIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type RequiredIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RequiredIf) Reset()         { *m = RequiredIf{} }
func (m *RequiredIf) String() string { return proto.CompactTextString(m) }
func (*RequiredIf) ProtoMessage()    {}
func (*RequiredIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{5}
}

func (m *RequiredIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequiredIf.Unmarshal(m, b)
}
func (m *RequiredIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequiredIf.Marshal(b, m, deterministic)
}
func (m *RequiredIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequiredIf.Merge(m, src)
}
func (m *RequiredIf) XXX_Size() int {
	return xxx_messageInfo_RequiredIf.Size(m)
}
func (m *RequiredIf) XXX_DiscardUnknown() {
	xxx_messageInfo_RequiredIf.DiscardUnknown(m)
}

var xxx_messageInfo_RequiredIf proto.InternalMessageInfo

func (m *RequiredIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type DisabledIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DisabledIf) Reset()         { *m = DisabledIf{} }
func (m *DisabledIf) String() string { return proto.CompactTextString(m) }
func (*DisabledIf) ProtoMessage()    {}
func (*DisabledIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{6}
}

func (m *DisabledIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisabledIf.Unmarshal(m, b)
}
func (m *DisabledIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisabledIf.Marshal(b, m, deterministic)
}
func (m *DisabledIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisabledIf.Merge(m, src)
}
func (m *DisabledIf) XXX_Size() int {
	return xxx_messageInfo_DisabledIf.Size(m)
}
func (m *DisabledIf) XXX_DiscardUnknown() {
	xxx_messageInfo_DisabledIf.DiscardUnknown(m)
}

var xxx_messageInfo_DisabledIf proto.InternalMessageInfo

func (m *DisabledIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type HiddenIf struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HiddenIf) Reset()         { *m = HiddenIf{} }
func (m *HiddenIf) String() string { return proto.CompactTextString(m) }
func (*HiddenIf) ProtoMessage()    {}
func (*HiddenIf) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{7}
}

func (m *HiddenIf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiddenIf.Unmarshal(m, b)
}
func (m *HiddenIf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiddenIf.Marshal(b, m, deterministic)
}
func (m *HiddenIf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiddenIf.Merge(m, src)
}
func (m *HiddenIf) XXX_Size() int {
	return xxx_messageInfo_HiddenIf.Size(m)
}
func (m *HiddenIf) XXX_DiscardUnknown() {
	xxx_messageInfo_HiddenIf.DiscardUnknown(m)
}

var xxx_messageInfo_HiddenIf proto.InternalMessageInfo

func (m *HiddenIf) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type Validator struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	TextIsEqual          string   `protobuf:"bytes,10,opt,name=text_is_equal,json=textIsEqual,proto3" json:"text_is_equal,omitempty"`
	LengthSmallerThan    int64    `protobuf:"varint,11,opt,name=length_smaller_than,json=lengthSmallerThan,proto3" json:"length_smaller_than,omitempty"`
	LengthGreaterThan    int64    `protobuf:"varint,12,opt,name=length_greater_than,json=lengthGreaterThan,proto3" json:"length_greater_than,omitempty"`
	NumberIsEqual        int64    `protobuf:"varint,20,opt,name=number_is_equal,json=numberIsEqual,proto3" json:"number_is_equal,omitempty"`
	NumberSmallerThan    int64    `protobuf:"varint,21,opt,name=number_smaller_than,json=numberSmallerThan,proto3" json:"number_smaller_than,omitempty"`
	NumberGreaterThan    int64    `protobuf:"varint,22,opt,name=number_greater_than,json=numberGreaterThan,proto3" json:"number_greater_than,omitempty"`
	MatchRegexPattern    string   `protobuf:"bytes,30,opt,name=match_regex_pattern,json=matchRegexPattern,proto3" json:"match_regex_pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{8}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Validator) GetTextIsEqual() string {
	if m != nil {
		return m.TextIsEqual
	}
	return ""
}

func (m *Validator) GetLengthSmallerThan() int64 {
	if m != nil {
		return m.LengthSmallerThan
	}
	return 0
}

func (m *Validator) GetLengthGreaterThan() int64 {
	if m != nil {
		return m.LengthGreaterThan
	}
	return 0
}

func (m *Validator) GetNumberIsEqual() int64 {
	if m != nil {
		return m.NumberIsEqual
	}
	return 0
}

func (m *Validator) GetNumberSmallerThan() int64 {
	if m != nil {
		return m.NumberSmallerThan
	}
	return 0
}

func (m *Validator) GetNumberGreaterThan() int64 {
	if m != nil {
		return m.NumberGreaterThan
	}
	return 0
}

func (m *Validator) GetMatchRegexPattern() string {
	if m != nil {
		return m.MatchRegexPattern
	}
	return ""
}

type TextField struct {
	Value                string    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Options              []*Option `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	Min                  int64     `protobuf:"varint,10,opt,name=min,proto3" json:"min,omitempty"`
	MinError             string    `protobuf:"bytes,20,opt,name=min_error,json=minError,proto3" json:"min_error,omitempty"`
	Max                  int64     `protobuf:"varint,11,opt,name=max,proto3" json:"max,omitempty"`
	MaxError             string    `protobuf:"bytes,21,opt,name=max_error,json=maxError,proto3" json:"max_error,omitempty"`
	Regex                string    `protobuf:"bytes,12,opt,name=regex,proto3" json:"regex,omitempty"`
	RegexError           string    `protobuf:"bytes,22,opt,name=regex_error,json=regexError,proto3" json:"regex_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TextField) Reset()         { *m = TextField{} }
func (m *TextField) String() string { return proto.CompactTextString(m) }
func (*TextField) ProtoMessage()    {}
func (*TextField) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{9}
}

func (m *TextField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextField.Unmarshal(m, b)
}
func (m *TextField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextField.Marshal(b, m, deterministic)
}
func (m *TextField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextField.Merge(m, src)
}
func (m *TextField) XXX_Size() int {
	return xxx_messageInfo_TextField.Size(m)
}
func (m *TextField) XXX_DiscardUnknown() {
	xxx_messageInfo_TextField.DiscardUnknown(m)
}

var xxx_messageInfo_TextField proto.InternalMessageInfo

func (m *TextField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TextField) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *TextField) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *TextField) GetMinError() string {
	if m != nil {
		return m.MinError
	}
	return ""
}

func (m *TextField) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *TextField) GetMaxError() string {
	if m != nil {
		return m.MaxError
	}
	return ""
}

func (m *TextField) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

func (m *TextField) GetRegexError() string {
	if m != nil {
		return m.RegexError
	}
	return ""
}

type SelectField struct {
	Index                int64      `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Type                 SelectType `protobuf:"varint,2,opt,name=type,proto3,enum=grpcform.SelectType" json:"type,omitempty"`
	Options              []*Option  `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	Error                string     `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SelectField) Reset()         { *m = SelectField{} }
func (m *SelectField) String() string { return proto.CompactTextString(m) }
func (*SelectField) ProtoMessage()    {}
func (*SelectField) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{10}
}

func (m *SelectField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectField.Unmarshal(m, b)
}
func (m *SelectField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectField.Marshal(b, m, deterministic)
}
func (m *SelectField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectField.Merge(m, src)
}
func (m *SelectField) XXX_Size() int {
	return xxx_messageInfo_SelectField.Size(m)
}
func (m *SelectField) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectField.DiscardUnknown(m)
}

var xxx_messageInfo_SelectField proto.InternalMessageInfo

func (m *SelectField) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SelectField) GetType() SelectType {
	if m != nil {
		return m.Type
	}
	return SelectType_SELECT_TYPE_UNSPECIFIED
}

func (m *SelectField) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *SelectField) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Option struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{11}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Option) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type NumericField struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Step                 int64    `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Min                  int64    `protobuf:"varint,10,opt,name=min,proto3" json:"min,omitempty"`
	MinError             string   `protobuf:"bytes,20,opt,name=min_error,json=minError,proto3" json:"min_error,omitempty"`
	Max                  int64    `protobuf:"varint,11,opt,name=max,proto3" json:"max,omitempty"`
	MaxError             string   `protobuf:"bytes,21,opt,name=max_error,json=maxError,proto3" json:"max_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumericField) Reset()         { *m = NumericField{} }
func (m *NumericField) String() string { return proto.CompactTextString(m) }
func (*NumericField) ProtoMessage()    {}
func (*NumericField) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{12}
}

func (m *NumericField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumericField.Unmarshal(m, b)
}
func (m *NumericField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumericField.Marshal(b, m, deterministic)
}
func (m *NumericField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumericField.Merge(m, src)
}
func (m *NumericField) XXX_Size() int {
	return xxx_messageInfo_NumericField.Size(m)
}
func (m *NumericField) XXX_DiscardUnknown() {
	xxx_messageInfo_NumericField.DiscardUnknown(m)
}

var xxx_messageInfo_NumericField proto.InternalMessageInfo

func (m *NumericField) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NumericField) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *NumericField) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *NumericField) GetMinError() string {
	if m != nil {
		return m.MinError
	}
	return ""
}

func (m *NumericField) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *NumericField) GetMaxError() string {
	if m != nil {
		return m.MaxError
	}
	return ""
}

type Button struct {
	Label                string         `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Status               ButtonStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=grpcform.ButtonStatus" json:"status,omitempty"`
	Type                 ButtonFuncType `protobuf:"varint,3,opt,name=type,proto3,enum=grpcform.ButtonFuncType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Button) Reset()         { *m = Button{} }
func (m *Button) String() string { return proto.CompactTextString(m) }
func (*Button) ProtoMessage()    {}
func (*Button) Descriptor() ([]byte, []int) {
	return fileDescriptor_875c494c6e4805a2, []int{13}
}

func (m *Button) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Button.Unmarshal(m, b)
}
func (m *Button) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Button.Marshal(b, m, deterministic)
}
func (m *Button) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Button.Merge(m, src)
}
func (m *Button) XXX_Size() int {
	return xxx_messageInfo_Button.Size(m)
}
func (m *Button) XXX_DiscardUnknown() {
	xxx_messageInfo_Button.DiscardUnknown(m)
}

var xxx_messageInfo_Button proto.InternalMessageInfo

func (m *Button) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Button) GetStatus() ButtonStatus {
	if m != nil {
		return m.Status
	}
	return ButtonStatus_BUTTON_STATUS_UNSPECIFIED
}

func (m *Button) GetType() ButtonFuncType {
	if m != nil {
		return m.Type
	}
	return ButtonFuncType_BUTTON_FUNC_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("grpcform.FieldStatus", FieldStatus_name, FieldStatus_value)
	proto.RegisterEnum("grpcform.SelectType", SelectType_name, SelectType_value)
	proto.RegisterEnum("grpcform.ButtonStatus", ButtonStatus_name, ButtonStatus_value)
	proto.RegisterEnum("grpcform.ButtonFuncType", ButtonFuncType_name, ButtonFuncType_value)
	proto.RegisterType((*GetFormRequest)(nil), "grpcform.GetFormRequest")
	proto.RegisterType((*SendFormResponse)(nil), "grpcform.SendFormResponse")
	proto.RegisterType((*Form)(nil), "grpcform.Form")
	proto.RegisterType((*Field)(nil), "grpcform.Field")
	proto.RegisterType((*ActiveIf)(nil), "grpcform.ActiveIf")
	proto.RegisterType((*RequiredIf)(nil), "grpcform.RequiredIf")
	proto.RegisterType((*DisabledIf)(nil), "grpcform.DisabledIf")
	proto.RegisterType((*HiddenIf)(nil), "grpcform.HiddenIf")
	proto.RegisterType((*Validator)(nil), "grpcform.Validator")
	proto.RegisterType((*TextField)(nil), "grpcform.TextField")
	proto.RegisterType((*SelectField)(nil), "grpcform.SelectField")
	proto.RegisterType((*Option)(nil), "grpcform.Option")
	proto.RegisterType((*NumericField)(nil), "grpcform.NumericField")
	proto.RegisterType((*Button)(nil), "grpcform.Button")
}

func init() { proto.RegisterFile("grpc-form.proto", fileDescriptor_875c494c6e4805a2) }

var fileDescriptor_875c494c6e4805a2 = []byte{
	// 1119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x8e, 0x44, 0xc5, 0x91, 0x46, 0xb2, 0x4d, 0xaf, 0x65, 0x85, 0x49, 0xfa, 0x13, 0x10, 0x45,
	0xeb, 0x1a, 0x8d, 0x5a, 0x38, 0x0d, 0x10, 0xa0, 0x87, 0x40, 0xb6, 0xe8, 0x84, 0x80, 0xa2, 0xb8,
	0x4b, 0xca, 0x68, 0x7b, 0x21, 0x68, 0x69, 0x6d, 0xb1, 0x10, 0x29, 0x85, 0x5c, 0x05, 0x0a, 0xd0,
	0x6b, 0xd1, 0x63, 0x0f, 0x05, 0xfa, 0x1c, 0x7d, 0xa1, 0x5e, 0xfa, 0x24, 0xc5, 0xce, 0x2e, 0xc5,
	0x15, 0xe3, 0xa0, 0x40, 0x80, 0xde, 0x76, 0xe6, 0xfb, 0xbe, 0xe1, 0xcc, 0xce, 0x72, 0x76, 0x61,
	0xf7, 0x3a, 0x5d, 0x8c, 0x1f, 0x5d, 0xcd, 0xd3, 0xb8, 0xbb, 0x48, 0xe7, 0x7c, 0x4e, 0xea, 0xc2,
	0x21, 0x6c, 0xfb, 0x33, 0xd8, 0x79, 0xce, 0xf8, 0xd9, 0x3c, 0x8d, 0x29, 0x7b, 0xbd, 0x64, 0x19,
	0x27, 0x04, 0x6a, 0x49, 0x18, 0x33, 0xab, 0xf2, 0xb0, 0x72, 0xd8, 0xa0, 0xb8, 0xb6, 0x7f, 0x06,
	0xd3, 0x63, 0xc9, 0x44, 0xd2, 0xb2, 0xc5, 0x3c, 0xc9, 0x18, 0xb1, 0xa1, 0x26, 0x22, 0x20, 0xaf,
	0x79, 0xbc, 0xd3, 0xcd, 0x43, 0x76, 0x91, 0x85, 0x18, 0xb1, 0xe0, 0x4e, 0xb6, 0x1c, 0x8f, 0x19,
	0x9b, 0x58, 0xd5, 0x87, 0x95, 0xc3, 0x3a, 0xcd, 0x4d, 0x81, 0xc4, 0x2c, 0xcb, 0xc2, 0x6b, 0x66,
	0x19, 0xf8, 0xa1, 0xdc, 0xb4, 0x7f, 0xad, 0x40, 0x4d, 0x84, 0xb8, 0x29, 0x11, 0xf2, 0x05, 0x6c,
	0x5d, 0x45, 0x6c, 0x36, 0xc9, 0xac, 0xea, 0x43, 0xe3, 0xb0, 0x79, 0xbc, 0xab, 0x7d, 0x56, 0xf8,
	0xa9, 0x82, 0xc9, 0x11, 0xdc, 0xb9, 0x5c, 0x72, 0x3e, 0x4f, 0x32, 0xcb, 0x40, 0xa6, 0x59, 0x30,
	0x4f, 0x10, 0xa0, 0x39, 0x81, 0xb4, 0xe1, 0xf6, 0x9b, 0x70, 0x16, 0x4d, 0xac, 0x1a, 0xe6, 0x28,
	0x0d, 0xfb, 0xb7, 0x1a, 0xdc, 0xc6, 0x98, 0x02, 0x9f, 0x85, 0x97, 0x6c, 0xa6, 0x32, 0x91, 0x06,
	0x79, 0x04, 0x5b, 0x19, 0x0f, 0xf9, 0x32, 0xc3, 0xd2, 0x76, 0x8e, 0x0f, 0x4a, 0xa9, 0x78, 0x08,
	0x52, 0x45, 0x22, 0x5f, 0x82, 0x19, 0x25, 0x19, 0x0f, 0x13, 0x1e, 0x60, 0xfc, 0x90, 0xcb, 0xca,
	0xeb, 0x74, 0x57, 0xf9, 0x2f, 0x94, 0x5b, 0x7c, 0x8f, 0xa5, 0xe9, 0x3c, 0xc5, 0x7c, 0x1a, 0x54,
	0x1a, 0xe4, 0x18, 0x80, 0xb3, 0x15, 0x0f, 0xb0, 0x40, 0x0b, 0x70, 0xd7, 0xf7, 0x8b, 0x6f, 0xfa,
	0x6c, 0xc5, 0xe5, 0x16, 0x34, 0x78, 0xbe, 0x24, 0x4f, 0xa1, 0x95, 0xb1, 0x19, 0x1b, 0xe7, 0xaa,
	0x26, 0xaa, 0xb4, 0x4c, 0x3d, 0x44, 0xa5, 0xae, 0x99, 0x15, 0x06, 0xf9, 0x0e, 0xb6, 0x93, 0x65,
	0xcc, 0xd2, 0x68, 0xac, 0xa4, 0x2d, 0x94, 0x76, 0x0a, 0xe9, 0x50, 0xc2, 0x52, 0xdb, 0x4a, 0x34,
	0x8b, 0x74, 0xa1, 0x1e, 0x8e, 0x79, 0xf4, 0x86, 0xb9, 0x57, 0x56, 0x1b, 0x75, 0xa4, 0xd0, 0xf5,
	0x14, 0x42, 0xd7, 0x1c, 0xf2, 0x04, 0x9a, 0x29, 0x7b, 0xbd, 0x8c, 0x52, 0x36, 0x09, 0xa2, 0x2b,
	0xeb, 0x00, 0x25, 0xed, 0x42, 0x42, 0x15, 0xe8, 0x5e, 0x51, 0x48, 0xd7, 0x6b, 0x21, 0x9b, 0x44,
	0x59, 0x78, 0x39, 0x93, 0xb2, 0x4e, 0x59, 0xd6, 0x57, 0xa0, 0x90, 0x4d, 0xd6, 0x6b, 0xf2, 0x35,
	0x34, 0xa6, 0xd1, 0x64, 0xc2, 0x12, 0x21, 0xba, 0x5b, 0x4e, 0xef, 0x05, 0x42, 0x22, 0xbd, 0xa9,
	0x5a, 0xd9, 0xcf, 0xa0, 0x9e, 0x27, 0x4d, 0x1e, 0x03, 0xa8, 0xf6, 0xcd, 0xd3, 0xcc, 0xaa, 0xe0,
	0xd1, 0xd2, 0xba, 0x70, 0x91, 0x63, 0x54, 0xa3, 0xd9, 0x3d, 0x80, 0xa2, 0x84, 0x0f, 0x0e, 0x51,
	0x94, 0xf3, 0x61, 0x21, 0x9e, 0x41, 0x3d, 0x2f, 0xee, 0xc3, 0x02, 0xfc, 0x5d, 0x85, 0xc6, 0x1a,
	0x11, 0xa7, 0x34, 0x4a, 0x26, 0x6c, 0x85, 0x7f, 0x85, 0x41, 0xa5, 0x41, 0x6c, 0xd8, 0xc6, 0x53,
	0x1a, 0x65, 0x01, 0x7b, 0xbd, 0x0c, 0x67, 0x78, 0x50, 0x1b, 0xb4, 0x29, 0x9c, 0x6e, 0xe6, 0x08,
	0x17, 0xe9, 0xc2, 0xfe, 0x8c, 0x25, 0xd7, 0x7c, 0x1a, 0x64, 0x71, 0x38, 0x9b, 0xb1, 0x34, 0xe0,
	0xd3, 0x30, 0xc1, 0xc3, 0x69, 0xd0, 0x3d, 0x09, 0x79, 0x12, 0xf1, 0xa7, 0x61, 0xa2, 0xf1, 0xaf,
	0x53, 0x16, 0xf2, 0x9c, 0xdf, 0xd2, 0xf9, 0xcf, 0x25, 0x82, 0xfc, 0xcf, 0x61, 0x37, 0x59, 0xc6,
	0x97, 0x2c, 0x2d, 0xb2, 0x68, 0x23, 0x77, 0x5b, 0xba, 0xb5, 0x3c, 0x14, 0x6f, 0x23, 0x8f, 0x03,
	0x19, 0x57, 0x42, 0xa5, 0x3c, 0x14, 0x7f, 0x23, 0x8f, 0x8e, 0xce, 0xd7, 0xf3, 0xe8, 0xc2, 0x7e,
	0x1c, 0xf2, 0xf1, 0x34, 0x48, 0xd9, 0x35, 0x5b, 0x05, 0x8b, 0x90, 0x73, 0x96, 0x26, 0xd6, 0x27,
	0xb8, 0x23, 0x7b, 0x08, 0x51, 0x81, 0x9c, 0x4b, 0xc0, 0xfe, 0xa7, 0x02, 0x8d, 0xf5, 0x6f, 0xac,
	0xa6, 0xd2, 0x32, 0x9f, 0x7f, 0xd2, 0x10, 0x73, 0x6d, 0xbe, 0xe0, 0x91, 0x98, 0x6b, 0xd5, 0xf2,
	0x5c, 0x7b, 0x85, 0x00, 0xcd, 0x09, 0xc4, 0x04, 0x23, 0x8e, 0x12, 0xec, 0x80, 0x41, 0xc5, 0x92,
	0x3c, 0x80, 0x46, 0x1c, 0x25, 0x81, 0x9c, 0x2e, 0x6d, 0x8c, 0x5b, 0x8f, 0xa3, 0xc4, 0xc1, 0x01,
	0x23, 0xe8, 0xe1, 0x4a, 0xb5, 0x41, 0x2c, 0x91, 0x1e, 0xae, 0x14, 0xfd, 0x40, 0xd1, 0xc3, 0x95,
	0xa4, 0xb7, 0xe1, 0x36, 0xd6, 0x85, 0x7d, 0x68, 0x50, 0x69, 0x90, 0x4f, 0xc5, 0xaf, 0x2c, 0xaa,
	0x95, 0xa2, 0x0e, 0x62, 0x80, 0x2e, 0x94, 0xd9, 0xbf, 0x57, 0xa0, 0xa9, 0x4d, 0x9d, 0xf7, 0x1c,
	0xa3, 0x43, 0xa8, 0xf1, 0xb7, 0x0b, 0xa6, 0x46, 0x6b, 0xbb, 0x3c, 0xb0, 0xfc, 0xb7, 0x0b, 0x46,
	0x91, 0xa1, 0x6f, 0x88, 0xf1, 0x5f, 0x1b, 0x72, 0xe3, 0x60, 0xb5, 0xbf, 0x85, 0x2d, 0x49, 0x7c,
	0x4f, 0x2e, 0xeb, 0x46, 0x54, 0xb5, 0x46, 0xd8, 0x7f, 0x56, 0xa0, 0xa5, 0x8f, 0xc0, 0xcd, 0x7e,
	0x19, 0x79, 0xbf, 0x08, 0xd4, 0x32, 0xce, 0x16, 0xa8, 0x35, 0x28, 0xae, 0xff, 0xdf, 0xbe, 0xd8,
	0xbf, 0xc0, 0x96, 0xbc, 0xe0, 0xde, 0x73, 0x6f, 0x75, 0x4b, 0xf7, 0x56, 0xa7, 0x7c, 0x31, 0x96,
	0x2e, 0xae, 0xaf, 0x54, 0x2b, 0x0c, 0x64, 0x5b, 0x65, 0xf6, 0xd9, 0x32, 0x19, 0x17, 0xed, 0x38,
	0xfa, 0xa3, 0x02, 0x4d, 0xed, 0xfa, 0x23, 0x1f, 0x81, 0x75, 0xe6, 0x3a, 0x83, 0x7e, 0xe0, 0xf9,
	0x3d, 0x7f, 0xe4, 0x05, 0xa3, 0xa1, 0x77, 0xee, 0x9c, 0xba, 0x67, 0xae, 0xd3, 0x37, 0x6f, 0x91,
	0xbb, 0xb0, 0xbf, 0x81, 0xf6, 0x4e, 0x7d, 0xf7, 0xc2, 0x31, 0x2b, 0xe4, 0x1e, 0x1c, 0x6c, 0x00,
	0xd4, 0xf9, 0x7e, 0xe4, 0x52, 0xa7, 0x6f, 0x56, 0xdf, 0x81, 0xfa, 0xae, 0xd7, 0x3b, 0x19, 0x38,
	0x7d, 0xd3, 0x78, 0x27, 0xdc, 0x0b, 0xb7, 0xdf, 0x77, 0x86, 0x66, 0xed, 0xe8, 0x07, 0x80, 0xe2,
	0xe0, 0x90, 0x07, 0x70, 0xd7, 0x73, 0x06, 0xce, 0xa9, 0x1f, 0xf8, 0x3f, 0x9e, 0x3b, 0xa5, 0x94,
	0x3a, 0x40, 0x74, 0xd0, 0x73, 0x5f, 0x9e, 0x0f, 0x44, 0x46, 0x07, 0xb0, 0xa7, 0xfb, 0x5f, 0x8e,
	0x06, 0xbe, 0x6b, 0x56, 0x8f, 0xa6, 0xd0, 0xd2, 0x77, 0x8d, 0x7c, 0x0c, 0xf7, 0x4e, 0x46, 0xbe,
	0xff, 0x6a, 0x78, 0x73, 0xc1, 0x7b, 0xb0, 0xad, 0xe0, 0x75, 0xa9, 0xfb, 0xb0, 0xab, 0x5c, 0x5a,
	0x25, 0x05, 0x6f, 0x5d, 0x03, 0x87, 0x9d, 0xcd, 0x1d, 0x17, 0x75, 0x28, 0xd2, 0xd9, 0x68, 0x78,
	0x5a, 0xfa, 0x92, 0x05, 0x6d, 0x1d, 0xbc, 0xe8, 0x0d, 0xdc, 0x7e, 0xcf, 0x57, 0x95, 0xe8, 0x08,
	0x75, 0x3c, 0xc7, 0x37, 0xab, 0xa4, 0x0d, 0xa6, 0xee, 0xf6, 0x9c, 0x61, 0xdf, 0x34, 0x8e, 0xff,
	0x12, 0xfd, 0x9c, 0xa7, 0xb1, 0xc7, 0xd2, 0x37, 0xd1, 0x98, 0x91, 0x27, 0x70, 0x47, 0xbd, 0x17,
	0x89, 0x76, 0x14, 0x36, 0x9f, 0x90, 0xf7, 0x4b, 0x8f, 0x41, 0xfb, 0x16, 0xf9, 0x06, 0x5a, 0xf9,
	0xf3, 0x06, 0xb5, 0x25, 0xc6, 0x0d, 0x8a, 0xa7, 0x50, 0xcf, 0x9f, 0x9c, 0xef, 0xb0, 0xef, 0xeb,
	0xf3, 0x60, 0xf3, 0x59, 0x6a, 0xdf, 0x3a, 0x81, 0x9f, 0xd6, 0xcf, 0xdb, 0xcb, 0x2d, 0x7c, 0xef,
	0x3e, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x86, 0xa4, 0x68, 0x02, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FormServiceClient is the client API for FormService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FormServiceClient interface {
	GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*Form, error)
	ValidateForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*Form, error)
	SendForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*SendFormResponse, error)
}

type formServiceClient struct {
	cc *grpc.ClientConn
}

func NewFormServiceClient(cc *grpc.ClientConn) FormServiceClient {
	return &formServiceClient{cc}
}

func (c *formServiceClient) GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*Form, error) {
	out := new(Form)
	err := c.cc.Invoke(ctx, "/grpcform.FormService/GetForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) ValidateForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*Form, error) {
	out := new(Form)
	err := c.cc.Invoke(ctx, "/grpcform.FormService/ValidateForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) SendForm(ctx context.Context, in *Form, opts ...grpc.CallOption) (*SendFormResponse, error) {
	out := new(SendFormResponse)
	err := c.cc.Invoke(ctx, "/grpcform.FormService/SendForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormServiceServer is the server API for FormService service.
type FormServiceServer interface {
	GetForm(context.Context, *GetFormRequest) (*Form, error)
	ValidateForm(context.Context, *Form) (*Form, error)
	SendForm(context.Context, *Form) (*SendFormResponse, error)
}

func RegisterFormServiceServer(s *grpc.Server, srv FormServiceServer) {
	s.RegisterService(&_FormService_serviceDesc, srv)
}

func _FormService_GetForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).GetForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcform.FormService/GetForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormServiceServer).GetForm(ctx, req.(*GetFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_ValidateForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Form)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).ValidateForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcform.FormService/ValidateForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormServiceServer).ValidateForm(ctx, req.(*Form))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_SendForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Form)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).SendForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcform.FormService/SendForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormServiceServer).SendForm(ctx, req.(*Form))
	}
	return interceptor(ctx, in, info, handler)
}

var _FormService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcform.FormService",
	HandlerType: (*FormServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetForm",
			Handler:    _FormService_GetForm_Handler,
		},
		{
			MethodName: "ValidateForm",
			Handler:    _FormService_ValidateForm_Handler,
		},
		{
			MethodName: "SendForm",
			Handler:    _FormService_SendForm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-form.proto",
}
